apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 59018
releaseNotes:
  - |
    **Fixed** Gateway API CORS origin parsing to properly handle wildcard origins and ignore unmatched preflights.
