apiVersion: release-notes/v2

kind: feature

area: installation

# issue is a list of GitHub issues resolved in this note.
# If issue is not in the current repo, specify its full URL instead.
issue:
  - 59168

# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
- |
  **Added** handling of `.Values.global.agentgateway.tolerations` and `.Values.global.agentgateway.affinity` for agent gateway.
  **Added** handling of `.Values.global.gateway.tolerations` and `.Values.global.gateway.affinity` for gateway.
  **Added** handling of `.Values.global.kube-gateway.tolerations` and `.Values.global.kube-gateway.affinity` for kube gateway.
  **Added** handling of `.Values.global.sidecar.tolerations` and `.Values.global.sidecar.affinity` for sidecar.

