apiVersion: release-notes/v2

kind: bug-fix

area: traffic-management

releaseNotes:
- |
  **Fixed** istiod crashing when `PILOT_ENABLE_AMBIENT=true`, but not
  `AMBIENT_ENABLE_MULTI_NETWORK` is set and a WorkloadEntry resource exists
  with a different network than the local cluster.
