apiVersion: release-notes/v2

kind: bug-fix
area: traffic-management

issue:
- 59433

# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
  - |
    **Fixed** GatewayAPI deployment controller will respect pre-existing servicetype
