apiVersion: release-notes/v2
kind: feature
area: ambient
releaseNotes:
  - |
    **Added** `WaypointBound` status condition to `WorkloadEntry` resources, reporting whether the workload is
    successfully attached to its waypoint proxy or if there was an error binding.
