apiVersion: release-notes/v2
kind: bug-fix
area: security
issue:
  - https://github.com/istio/istio/issues/61075
releaseNotes:
- |
  **Fixed** a bug where an invalid CRL would prevent certificate rotation.
