apiVersion: release-notes/v2
kind: bug-fix
area: security
issue:
  - https://github.com/istio/istio/issues/61073
releaseNotes:
- |
  **Added** the ability to clear the Certificate Revocation List (CRL) by specifying the empty string as the ca-crl.pem.
