apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
  - 61502

releaseNotes:
- |
  **Fixed** an issue where istiod repeatedly serialized the same workload when
  pushing workload metadata to Envoy proxies.
