apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management

issue:
  - 61728

releaseNotes:
  - |
    **Fixed** waypoints being configured with the double HBONE resources even when `AMBIENT_ENABLE_MULTI_NETWORK` was disabled.
