apiVersion: release-notes/v2
kind: feature
area: traffic-management
issue:
  - 59083

releaseNotes:
  - |
    **Added** an `istio.io/connect-strategy` annotation to ServiceEntries to allow different DNS connection semantics. Users can set this to `RACE_FIRST_TCP_CONNECT` when DNS servers return multiple A records and the client should test each endpoint and pick the first one that results in a successful TCP connection.
