apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
  - |
    **Added** support for overriding the ALPN protocols advertised by TLS-terminating gateways with the Gateway
    resource's `alpnProtocols` field.
