apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
- |
  **Optimized** pushes to proxyless gRPC clients by skipping listener, cluster and route generation
    for updates that do not affect hostnames the client actually subscribes to.
