apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
- |
  **Fixed** an issue where EDS-irrelevant configuration updates coalesced with an endpoint update
  caused full EDS generation instead of updating only the affected endpoint assignments.
