apiVersion: release-notes/v2
kind: bug-fix
area: installation
issue: []
releaseNotes:
- |
  **Fixed** an issue where numeric or boolean-looking revision tags generated invalid Kubernetes labels in the Istiod Helm chart.
