apiVersion: release-notes/v2
kind: feature
area: security
releaseNotes:
  - |
    **Added** a new environment variable `PILOT_ENABLE_REMOTE_CREDENTIALS_CONTROLLER` (default `true`) which toggles credential controllers for remote clusters.
