apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
  - |
    **Fixed** ServiceEntries with a present but empty workload selector incorrectly matching all workloads in their namespace.
