apiVersion: release-notes/v2
kind: feature
area: extensibility
issue:
  - 59322

releaseNotes:
- |
  **Added** support for configuring the Wasm binary size limit via the
  `ISTIO_WASM_MAX_BINARY_SIZE_BYTES` environment variable.
