package(default_visibility = ["//mixer/tools/codegen/pkg/interfacegen:__pkg__"])

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "interface.go",
        "templateproto.go",
    ],
)
