# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/mcp/v1alpha1/envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from config.mcp.v1alpha1 import metadata_pb2 as config_dot_mcp_dot_v1alpha1_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config/mcp/v1alpha1/envelope.proto',
  package='istio.config.mcp.v1alpha1',
  syntax='proto3',
  serialized_pb=_b('\n\"config/mcp/v1alpha1/envelope.proto\x12\x19istio.config.mcp.v1alpha1\x1a\x19google/protobuf/any.proto\x1a\"config/mcp/v1alpha1/metadata.proto\"i\n\x08\x45nvelope\x12\x35\n\x08metadata\x18\x01 \x01(\x0b\x32#.istio.config.mcp.v1alpha1.Metadata\x12&\n\x08resource\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\"Z istio.io/api/config/mcp/v1alpha1b\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,config_dot_mcp_dot_v1alpha1_dot_metadata__pb2.DESCRIPTOR,])




_ENVELOPE = _descriptor.Descriptor(
  name='Envelope',
  full_name='istio.config.mcp.v1alpha1.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='istio.config.mcp.v1alpha1.Envelope.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource', full_name='istio.config.mcp.v1alpha1.Envelope.resource', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=233,
)

_ENVELOPE.fields_by_name['metadata'].message_type = config_dot_mcp_dot_v1alpha1_dot_metadata__pb2._METADATA
_ENVELOPE.fields_by_name['resource'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Envelope = _reflection.GeneratedProtocolMessageType('Envelope', (_message.Message,), dict(
  DESCRIPTOR = _ENVELOPE,
  __module__ = 'config.mcp.v1alpha1.envelope_pb2'
  # @@protoc_insertion_point(class_scope:istio.config.mcp.v1alpha1.Envelope)
  ))
_sym_db.RegisterMessage(Envelope)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z istio.io/api/config/mcp/v1alpha1'))
# @@protoc_insertion_point(module_scope)
