FROM ubuntu:xenial
# Base image for debug builds.
# Built manually uploaded as "istionightly/base_debug"

ENV DEBIAN_FRONTEND=noninteractive

# Do not add more stuff to this list that isn't small or critically useful.
# If you occasionally need something on the container do
# sudo apt-get update && apt-get whichever

# hadolint ignore=DL3005,DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      iptables \
      iproute2 \
      iputils-ping \
      knot-dnsutils \
      netcat \
      tcpdump \
      net-tools \
      lsof \
      linux-tools-generic \
      sudo \
   && update-ca-certificates \
   && apt-get upgrade -y \
   && apt-get clean \
   && rm -rf  /var/log/*log /var/lib/apt/lists/* /var/log/apt/* /var/lib/dpkg/*-old /var/cache/debconf/*-old

# Sudoers used to allow tcpdump and other debug utilities.
RUN useradd -m --uid 1337 istio-proxy && \
    echo "istio-proxy ALL=NOPASSWD: ALL" >> /etc/sudoers

# Add a user that will run the application. This allows running as this user and capture iptables
RUN useradd -m --uid 1338 application && \
    echo "application ALL=NOPASSWD: ALL" >> /etc/sudoers

# Install the certs.
COPY certs/                           /var/lib/istio/
COPY certs/default/*                  /var/run/secrets/istio/

# Install the sidecar components
COPY istio-sidecar.deb  /tmp/istio-sidecar.deb
RUN dpkg -i /tmp/istio-sidecar.deb && rm /tmp/istio-sidecar.deb

# Install the Echo application
COPY echo-start.sh /usr/local/bin/echo-start.sh
COPY client /usr/local/bin/client
COPY server /usr/local/bin/server
RUN chmod +x /usr/local/bin/client /usr/local/bin/server

ENTRYPOINT ["/usr/local/bin/echo-start.sh"]
