package(default_visibility = ["//mixer/tools/codegen/pkg/bootstrapgen:__pkg__"])

filegroup(
    name = "descriptor_set",
    testonly = True,
    srcs = [
        "template_proto.descriptor_set",
    ],
)
