filegroup(
    name = "bookinfo",
    srcs = [
        "bookinfo.yaml",
        "mixer-rule-additional-telemetry.yaml",
        "mixer-rule-empty-rule.yaml",
        "mixer-rule-ratings-denial.yaml",
        "mixer-rule-ratings-ratelimit.yaml",
        "route-rule-all-v1.yaml",
        "route-rule-delay.yaml",
        "route-rule-reviews-50-v3.yaml",
        "route-rule-reviews-test-v2.yaml",
        "route-rule-reviews-v2-v3.yaml",
	"route-rule-ratings-mysql.yaml"
    ],
    visibility = ["//visibility:public"],
)
