# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

FROM istionightly/base_debug as default

FROM gcr.io/distroless/static as distroless

FROM ${BASE_DISTRIBUTION}
ADD mixer-test-policybackend /usr/local/bin/policybackend
ENTRYPOINT ["/usr/local/bin/policybackend", "server"]
