# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

FROM scratch as default

FROM gcr.io/distroless/static as distroless

FROM ${BASE_DISTRIBUTION}

ADD mixgen /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mixgen"]
