# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

FROM docker.io/istio/base:${BASE_VERSION}

COPY mixs /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
