# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

# ISTIO_VERSION is used to specify the version of the release
ARG ISTIO_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
# hadolint ignore=DL3006
FROM docker.io/istio/base:${ISTIO_VERSION} as default

# The following section is used as base image if BASE_DISTRIBUTION=distroless
# hadolint ignore=DL3007
FROM gcr.io/distroless/static:latest as distroless

# This will build the final image based on either default or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION}
COPY mixer-test-policybackend /usr/local/bin/policybackend
ENTRYPOINT ["/usr/local/bin/policybackend", "server"]
