version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "!/samples"
    schedule:
      interval: "daily"
    labels:
      - "release-notes-none"
    target-branch: "master"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "!/samples"
    schedule:
      interval: "daily"
    labels:
      - "release-notes-none"
    target-branch: "release-1.29"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "!/samples"
    schedule:
      interval: "daily"
    labels:
      - "release-notes-none"
    target-branch: "release-1.28"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "!/samples"
    schedule:
      interval: "daily"
    labels:
      - "release-notes-none"
    target-branch: "release-1.27"
    groups:
      all-dependencies:
        patterns:
          - "*"
