package(default_visibility = ["//example/servicegraph:__subpackages__"])

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["servicegraph.go"],
    visibility = ["//visibility:public"],
)
