filegroup(
    name = "bookinfo_out",
    srcs = [
        "productpage-normal-user-v1.html",
        "productpage-normal-user-v3.html",
        "productpage-test-user-v1-review-timeout.html",
        "productpage-test-user-v2.html",
    ],
    visibility = ["//visibility:public"],
)
