filegroup(
    name = "addons",
    srcs = [
        "grafana.yaml.tmpl",
        "prometheus.yaml.tmpl",
        "servicegraph.yaml.tmpl",
        "zipkin.yaml.tmpl",
        "zipkin-to-stackdriver.yaml.tmpl",
    ],
    visibility = ["//visibility:public"],
)
