load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "fakefileutil.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//auth/pkg/util:go_default_library",
    ],
)
