{
 "title": "Istio Canonical Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Canonical Service",
    "query": "label_values(destination_canonical_service)"
   },
   { "name": "qrep", "label": "Reporter", "query": "label_values(reporter)" },
   {
    "name": "srcns",
    "label": "Inbound Canonical Service Namespace",
    "query": "query_result(sum(istio_requests_total{reporter=\"$qrep\", destination_canonical_service=\"$service\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"$qrep\", destination_canonical_service=~\"$service\"}) by (source_workload_namespace))"
   },
   {
    "name": "dstns",
    "label": "Outbound Canonical Service Namespace",
    "query": "query_result(sum(istio_requests_total{reporter=\"destination\", source_canonical_service=\"$service\"}) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", source_canonical_service=~\"$service\"}) by (destination_workload_namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<div class=\"dashboard-header text-center\">\n<span>CANONICAL SERVICE: $service</span>\n</div>"
     },
     "content": "<div class=\"dashboard-header text-center\">\n<span>CANONICAL SERVICE: $service</span>\n</div>"
    },
    {
     "title": "Incoming Request Volume",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "format": "ops",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[5m])), 0.001)"
      }
     ]
    },
    {
     "title": "Incoming Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\",destination_canonical_service=~\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[5m]))"
      }
     ]
    },
    {
     "title": "Incoming Request Duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\",destination_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "TCP Received Bytes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\", destination_canonical_service=~\"$service\"}[1m]))"
      }
     ]
    },
    {
     "title": "Outgoing Request Volume",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "format": "ops",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",source_canonical_service=~\"$service\"}[5m])), 0.001)"
      }
     ]
    },
    {
     "title": "Outgoing Success Rate (non-5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "format": "percentunit",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\",source_canonical_service=~\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\",source_canonical_service=~\"$service\"}[5m]))"
      }
     ]
    },
    {
     "title": "Outgoing Request Duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",source_canonical_service=~\"$service\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "TCP Sent Bytes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
     "format": "Bps",
     "valueName": "avg",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"$qrep\", source_canonical_service=~\"$service\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound Canonical Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "<div class=\"dashboard-header text-center\">\n<span>INBOUND CANONICAL SERVICES</span>\n</div>"
     },
     "content": "<div class=\"dashboard-header text-center\">\n<span>INBOUND CANONICAL SERVICES</span>\n</div>"
    },
    {
     "title": "Incoming Requests By Source And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_canonical_service=~\"$service\",reporter=\"$qrep\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_canonical_service }}: {{ response_code }} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", reporter=\"$qrep\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_canonical_service }} : {{ response_code }}"
      }
     ]
    },
    {
     "title": "Incoming Success Rate (non-5xx responses) By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\",response_code!~\"5.*\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace)",
       "legendFormat": "{{ source_canonical_service }} (🔐mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\",response_code!~\"5.*\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[5m])) by (source_canonical_service, source_workload_namespace)",
       "legendFormat": "{{ source_canonical_service }}"
      }
     ]
    },
    {
     "title": "Incoming Request Duration By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P90 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P99 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P90"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P99"
      }
     ]
    },
    {
     "title": "Incoming Request Size By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}}  P90 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}}  P99 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P99"
      }
     ]
    },
    {
     "title": "Response Size By Source",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service,  source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}}  P90 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}}  P99 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace, le))",
       "legendFormat": "{{source_canonical_service}} P99"
      }
     ]
    },
    {
     "title": "Bytes Received from Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\", connection_security_policy=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_canonical_service}} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"$qrep\", connection_security_policy!=\"mutual_tls\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_canonical_service}}"
      }
     ]
    },
    {
     "title": "Bytes Sent to Incoming TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"$qrep\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_canonical_service}} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"$qrep\", destination_canonical_service=~\"$service\", source_workload_namespace=\"$srcns\"}[1m])) by (source_canonical_service, source_workload_namespace), 0.001)",
       "legendFormat": "{{source_canonical_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Canonical Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "<div class=\"dashboard-header text-center\">\n<span>OUTBOUND CANONICAL SERVICES</span>\n</div>"
     },
     "content": "<div class=\"dashboard-header text-center\">\n<span>OUTBOUND CANONICAL SERVICES</span>\n</div>"
    },
    {
     "title": "Outgoing Requests By Destination And Response Code",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",source_canonical_service=~\"$service\",reporter=\"destination\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{destination_canonical_service}} : {{ response_code }} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", reporter=\"destination\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{destination_canonical_service}} : {{ response_code }}"
      }
     ]
    },
    {
     "title": "Incoming Success Rate (non-5xx responses) By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\",response_code!~\"5.*\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace)",
       "legendFormat": "{{ destination_canonical_service }} (🔐mTLS)"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\",response_code!~\"5.*\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[5m])) by (destination_canonical_service, destination_workload_namespace)",
       "legendFormat": "{{ destination_canonical_service }}"
      }
     ]
    },
    {
     "title": "Outgoing Request Duration By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P90 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P99 (🔐mTLS)"
      },
      {
       "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50"
      },
      {
       "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P90"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P99"
      }
     ]
    },
    {
     "title": "Outgoing Request Size By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }}  P90 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }}  P99 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P99"
      }
     ]
    },
    {
     "title": "Response Size By Destination",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }}  P90 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }}  P99 (🔐mTLS)"
      },
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace, le))",
       "legendFormat": "{{ destination_canonical_service }} P99"
      }
     ]
    },
    {
     "title": "Bytes Sent on Outgoing TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"destination\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace), 0.001)",
       "legendFormat": "{{ destination_canonical_service }} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"destination\", source_canonical_service=~\"$service\", destination_workload_namespace=\"$dstns\"}[1m])) by (destination_canonical_service, destination_workload_namespace), 0.001)",
       "legendFormat": "{{ destination_canonical_service }}"
      }
     ]
    },
    {
     "title": "Bytes Received from Outgoing TCP Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", source_canonical_service=~\"$service\"}[1m])) by (destination_canonical_service), 0.001)",
       "legendFormat": "{{ destination_canonical_service }} (🔐mTLS)"
      },
      {
       "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", source_canonical_service=~\"$service\"}[1m])) by (destination_canonical_service), 0.001)",
       "legendFormat": "{{ destination_canonical_service }}"
      }
     ]
    }
   ]
  }
 ]
}