package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "listChecker.go",
    ],
    deps = [
        "//pkg/adapter:go_default_library",
    ],
)
