filegroup(
    name = "kubernetes",
    srcs = [
        "istio.yaml",
        "istio-auth.yaml",
        "istio-cluster-wide.yaml",
        "istio-rbac-beta.yaml",
    ],
    visibility = ["//visibility:public"],
)
