filegroup(
    name = "kubernetes",
    srcs = [
        "istio.yaml",
        "istio-auth.yaml",
        "istio-initializer.yaml",
        "istio-one-namespace.yaml",
        "istio-one-namespace-auth.yaml",
    ],
    visibility = ["//visibility:public"],
)
