{
 "title": "Istio Citadel Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage across Citadel instances.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"citadel\", pod_name=~\"istio-citadel-.*\"}[1m]))",
     "legendFormat": "Citadel CPU usage rate"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"citadel\"}[1m])",
     "legendFormat": "Citadel CPU usage irate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Citadel process memory statistics.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"citadel\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"citadel\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Memory Total"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Memory Allocated"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"citadel\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CSR Requests",
   "type": "graph",
   "description": "Total number of CSR requests made to Citadel.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_csr_count{job=\"citadel\"}",
     "legendFormat": "CSR Request Count"
    }
   ]
  },
  {
   "title": "Certificates Issued",
   "type": "graph",
   "description": "The number of certificates issuances that have succeeded.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_success_cert_issuance_count{job=\"citadel\"}",
     "legendFormat": "Certificates Issued"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CSR Creation Errors",
   "type": "graph",
   "description": "The number of errors occurred when creating the CSR.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_csr_err_count{job=\"citadel\"}",
     "legendFormat": "CSR Creation Error Count"
    }
   ]
  },
  {
   "title": "CSR Parse Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_csr_parsing_err_count{job=\"citadel\"}",
     "legendFormat": "CSR Parse Error Count"
    }
   ]
  },
  {
   "title": "Authentication Failures",
   "type": "graph",
   "description": "The number of authentication failures.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_authentication_failure_count{job=\"citadel\"}",
     "legendFormat": "Authentication Failure Count"
    }
   ]
  },
  { "title": "Secret Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Service Account Secrets Created (due to SA creation)",
   "type": "graph",
   "description": "The number of certificates created due to service account creation.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_svc_acc_created_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Created"
    }
   ]
  },
  {
   "title": "Service Account Secrets Deleted (due to SA deletion)",
   "type": "graph",
   "description": "The number of certificates deleted due to service account deletion.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_svc_acc_deleted_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Deleted"
    }
   ]
  },
  {
   "title": "Service Account Secrets Recreated (due to errant deletion)",
   "type": "graph",
   "description": "The number of certificates recreated due to secret deletion (service account still exists).",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_secret_deleted_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Recreated"
    }
   ]
  }
 ]
}