{
 "title": "Istio Galley Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Galley Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"galley\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"galley\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"galley\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"galley\"}",
     "legendFormat": "heap sys"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"galley\"}",
     "legendFormat": "heap alloc"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"galley\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"galley\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"galley\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"})",
     "legendFormat": "Total (kis)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}[1m])) by (container)",
     "legendFormat": "{{ container }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"galley\"}[1m])",
     "legendFormat": "galley (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"galley\"}",
     "legendFormat": "Open FDs (galley)"
    },
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}",
     "legendFormat": "{{ container }} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"galley\"}",
     "legendFormat": "goroutines_total"
    },
    {
     "expr": "istio_mcp_clients_total{component=\"galley\"}",
     "legendFormat": "clients_total"
    },
    {
     "expr": "go_goroutines{job=\"galley\"}/sum(istio_mcp_clients_total{component=\"galley\"}) without (component)",
     "legendFormat": "avg_goroutines_per_client"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Event Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_on_change_total[1m])) * 60",
     "legendFormat": "Strategy Change Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_events_processed_total[1m])) * 60",
     "legendFormat": "Processed Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_snapshots_published_total[1m])) * 60",
     "legendFormat": "Snapshot Published"
    }
   ]
  },
  {
   "title": "Timer Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_max_time_reached_total[1m])) * 60",
     "legendFormat": "Max Time Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_quiesce_reached_total[1m])) * 60",
     "legendFormat": "Quiesce Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_resets_total[1m])) * 60",
     "legendFormat": "Timer Resets"
    }
   ]
  },
  {
   "title": "Events Per Snapshot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "State Type Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (galley_runtime_state_type_instances_total)",
     "legendFormat": "{{ collection }}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Validation Webhook Certificate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "galley_validation_cert_key_updates{}",
     "legendFormat": "Key Updates"
    },
    {
     "expr": "galley_validation_cert_key_update_errors{}",
     "legendFormat": "Key Update Errors: {{ error }}"
    }
   ]
  },
  {
   "title": "Resource Validation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_passed{}) by (group, version, resource)",
     "legendFormat": "Passed: {{ group }}/{{ version }}/{{resource}}"
    },
    {
     "expr": "sum(galley_validation_failed{}) by (group, version, resource, reason)",
     "legendFormat": "Failed: {{ group }}/{{ version }}/{{resource}} ({{ reason}})"
    }
   ]
  },
  {
   "title": "Validation HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_http_error{}) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Kubernetes Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Source Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_source_kube_event_success_total[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(galley_source_kube_event_error_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Kubernetes Object Conversion Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Failures/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_source_kube_dynamic_converter_failure_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Mesh Configuration Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_mcp_clients_total{component=\"galley\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Request ACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "ACKs/min" }
   ],
   "targets": [
    {
     "expr": "sum by(collection)(irate(istio_mcp_request_acks_total{component=\"galley\"}[1m]) * 60)"
    }
   ]
  },
  {
   "title": "Request NACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "NACKs/min" }
   ],
   "targets": [
    {
     "expr": "rate(istio_mcp_request_nacks_total{component=\"galley\"}[1m]) * 60"
    }
   ]
  }
 ]
}