# Copyright 2021 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

FROM golang:1.15

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    clang && \
    apt-get clean && \
    rm -rf  /var/log/*log \
    /var/lib/apt/lists/* \
    /var/log/apt/* \
    /var/lib/dpkg/*-old \
    /var/cache/debconf/*-old

RUN go get -u github.com/dvyukov/go-fuzz/go-fuzz \
    github.com/dvyukov/go-fuzz/go-fuzz-dep \
    github.com/dvyukov/go-fuzz/go-fuzz-build

COPY . /istio
WORKDIR /istio

