# starts graphana with Prometheus Datasource pre configured
# imports dashboard /grafana-dashboard.json from DASHBOARD_URL
ARG grafana_base
from ${grafana_base}

COPY grafana.ini /etc/grafana/
COPY dashboards.yaml /etc/grafana/provisioning/dashboards/
COPY datasources.yaml /etc/grafana/provisioning/datasources/
COPY dashboards /var/lib/grafana/dashboards/
