from grafana/grafana:5.2.3

USER root

COPY grafana.ini /etc/grafana/
RUN chmod 777 -R /etc/grafana/

COPY dashboards.yaml /etc/grafana/provisioning/dashboards/
RUN chmod 777 -R /etc/grafana/provisioning/dashboards/

COPY datasources.yaml /etc/grafana/provisioning/datasources/
RUN chmod 777 -R /etc/grafana/provisioning/datasources/

COPY dashboards /var/lib/grafana/dashboards/
RUN chmod 777 -R /var/lib/grafana/dashboards/

USER grafana
