FROM grafana/grafana:5.2.1

COPY --chown=grafana grafana.ini /etc/grafana/
COPY --chown=grafana dashboards.yaml /etc/grafana/provisioning/dashboards/
COPY --chown=grafana datasources.yaml /etc/grafana/provisioning/datasources/

USER root
RUN mkdir -p /var/lib/grafana/dashboards && \
    chown grafana /var/lib/grafana/dashboards

RUN mkdir -p /data/grafana
RUN chown grafana /data/grafana
USER grafana

COPY --chown=grafana dashboards /var/lib/grafana/dashboards/
