package(default_visibility = ["//mixer/tools/codegen/pkg/modelgen:__pkg__"])

filegroup(
    name = "test_descriptors",
    testonly = True,
    srcs = [
        "basic_top_level_fields.descriptor_set",
        "missing_both_required.descriptor_set",
        "missing_package_name.descriptor_set",
        "missing_template_message.descriptor_set",
        "missing_template_variety.descriptor_set",
        "proto2_bad_syntax.descriptor_set",
        "reserved_field_in_template.descriptor_set",
        "simple_apa_template.descriptor_set",
        "simple_template.descriptor_set",
        "unsupported_field_type_as_map.descriptor_set",
        "unsupported_field_type_enum.descriptor_set",
        "unsupported_field_type_primitive.descriptor_set",
        "unsupported_valuetype_in_apa.descriptor_set",
        "wrong_pkg_name.descriptor_set",
    ],
)
