// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: test/echo/proto/echo.proto

// Generate with protoc --go_out=. echo.proto -I /work/common-protos/ -I.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyProtoVersion int32

const (
	ProxyProtoVersion_NONE ProxyProtoVersion = 0
	ProxyProtoVersion_V1   ProxyProtoVersion = 1
	ProxyProtoVersion_V2   ProxyProtoVersion = 2
)

// Enum value maps for ProxyProtoVersion.
var (
	ProxyProtoVersion_name = map[int32]string{
		0: "NONE",
		1: "V1",
		2: "V2",
	}
	ProxyProtoVersion_value = map[string]int32{
		"NONE": 0,
		"V1":   1,
		"V2":   2,
	}
)

func (x ProxyProtoVersion) Enum() *ProxyProtoVersion {
	p := new(ProxyProtoVersion)
	*p = x
	return p
}

func (x ProxyProtoVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyProtoVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_test_echo_proto_echo_proto_enumTypes[0].Descriptor()
}

func (ProxyProtoVersion) Type() protoreflect.EnumType {
	return &file_test_echo_proto_echo_proto_enumTypes[0]
}

func (x ProxyProtoVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyProtoVersion.Descriptor instead.
func (ProxyProtoVersion) EnumDescriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{0}
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ForwardEchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Qps           int32                  `protobuf:"varint,2,opt,name=qps,proto3" json:"qps,omitempty"`
	TimeoutMicros int64                  `protobuf:"varint,3,opt,name=timeout_micros,json=timeoutMicros,proto3" json:"timeout_micros,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// Method for the request. Valid only for HTTP
	Method string `protobuf:"bytes,9,opt,name=method,proto3" json:"method,omitempty"`
	// If true, requests will be sent using h2c prior knowledge
	Http2 bool `protobuf:"varint,7,opt,name=http2,proto3" json:"http2,omitempty"`
	// If true, requests will be sent using http3
	Http3 bool `protobuf:"varint,15,opt,name=http3,proto3" json:"http3,omitempty"`
	// If true, requests will not be sent until magic string is received
	ServerFirst bool `protobuf:"varint,8,opt,name=serverFirst,proto3" json:"serverFirst,omitempty"`
	// If true, 301 redirects will be followed
	FollowRedirects bool `protobuf:"varint,14,opt,name=followRedirects,proto3" json:"followRedirects,omitempty"`
	// If non-empty, make the request with the corresponding cert and key.
	Cert string `protobuf:"bytes,10,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,11,opt,name=key,proto3" json:"key,omitempty"`
	// If non-empty, verify the server CA
	CaCert string `protobuf:"bytes,12,opt,name=caCert,proto3" json:"caCert,omitempty"`
	// If non-empty, make the request with the corresponding cert and key file.
	CertFile string `protobuf:"bytes,16,opt,name=certFile,proto3" json:"certFile,omitempty"`
	KeyFile  string `protobuf:"bytes,17,opt,name=keyFile,proto3" json:"keyFile,omitempty"`
	// If non-empty, verify the server CA with the ca cert file.
	CaCertFile string `protobuf:"bytes,18,opt,name=caCertFile,proto3" json:"caCertFile,omitempty"`
	// Skip verifying peer's certificate.
	InsecureSkipVerify bool `protobuf:"varint,19,opt,name=insecureSkipVerify,proto3" json:"insecureSkipVerify,omitempty"`
	// List of ALPNs to present. If not set, this will be automatically be set based on the protocol
	Alpn *Alpn `protobuf:"bytes,13,opt,name=alpn,proto3" json:"alpn,omitempty"`
	// Server name (SNI) to present in TLS connections. If not set, Host will be used for http requests.
	ServerName string `protobuf:"bytes,20,opt,name=serverName,proto3" json:"serverName,omitempty"`
	// Expected response determines what string to look for in the response to validate TCP requests succeeded.
	// If not set, defaults to "StatusCode=200"
	ExpectedResponse *wrapperspb.StringValue `protobuf:"bytes,21,opt,name=expectedResponse,proto3" json:"expectedResponse,omitempty"`
	// If set, a new connection will be made to the server for each individual request. If false, an attempt
	// will be made to re-use the connection for the life of the forward request. This is automatically
	// set for DNS, TCP, TLS, and WebSocket protocols.
	NewConnectionPerRequest bool `protobuf:"varint,22,opt,name=newConnectionPerRequest,proto3" json:"newConnectionPerRequest,omitempty"`
	// If set, each request will force a DNS lookup. Only applies if newConnectionPerRequest is set.
	ForceDNSLookup bool `protobuf:"varint,23,opt,name=forceDNSLookup,proto3" json:"forceDNSLookup,omitempty"`
	// force_ip_family will force a specific IP family to be used for DNS resolution only.
	// Valid values: "tcp4", "tcp6".
	ForceIpFamily string `protobuf:"bytes,26,opt,name=force_ip_family,json=forceIpFamily,proto3" json:"force_ip_family,omitempty"`
	// HBONE communication settings. If provided, requests will be tunnelled.
	Hbone *HBONE `protobuf:"bytes,24,opt,name=hbone,proto3" json:"hbone,omitempty"`
	// Double HBONE communication settings. The settings here represent the outer
	// tunnel and the inner tunnel settigns are specified in the hbone field.
	// If the inner tunnel is not specified, the inner tunnel will
	// be the same as the outer tunnel.
	DoubleHbone          *HBONE            `protobuf:"bytes,27,opt,name=double_hbone,json=doubleHbone,proto3" json:"double_hbone,omitempty"`
	ProxyProtocolVersion ProxyProtoVersion `protobuf:"varint,25,opt,name=proxyProtocolVersion,proto3,enum=proto.ProxyProtoVersion" json:"proxyProtocolVersion,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ForwardEchoRequest) Reset() {
	*x = ForwardEchoRequest{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEchoRequest) ProtoMessage() {}

func (x *ForwardEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEchoRequest.ProtoReflect.Descriptor instead.
func (*ForwardEchoRequest) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardEchoRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ForwardEchoRequest) GetQps() int32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *ForwardEchoRequest) GetTimeoutMicros() int64 {
	if x != nil {
		return x.TimeoutMicros
	}
	return 0
}

func (x *ForwardEchoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ForwardEchoRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardEchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForwardEchoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardEchoRequest) GetHttp2() bool {
	if x != nil {
		return x.Http2
	}
	return false
}

func (x *ForwardEchoRequest) GetHttp3() bool {
	if x != nil {
		return x.Http3
	}
	return false
}

func (x *ForwardEchoRequest) GetServerFirst() bool {
	if x != nil {
		return x.ServerFirst
	}
	return false
}

func (x *ForwardEchoRequest) GetFollowRedirects() bool {
	if x != nil {
		return x.FollowRedirects
	}
	return false
}

func (x *ForwardEchoRequest) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *ForwardEchoRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardEchoRequest) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *ForwardEchoRequest) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ForwardEchoRequest) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ForwardEchoRequest) GetCaCertFile() string {
	if x != nil {
		return x.CaCertFile
	}
	return ""
}

func (x *ForwardEchoRequest) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *ForwardEchoRequest) GetAlpn() *Alpn {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *ForwardEchoRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ForwardEchoRequest) GetExpectedResponse() *wrapperspb.StringValue {
	if x != nil {
		return x.ExpectedResponse
	}
	return nil
}

func (x *ForwardEchoRequest) GetNewConnectionPerRequest() bool {
	if x != nil {
		return x.NewConnectionPerRequest
	}
	return false
}

func (x *ForwardEchoRequest) GetForceDNSLookup() bool {
	if x != nil {
		return x.ForceDNSLookup
	}
	return false
}

func (x *ForwardEchoRequest) GetForceIpFamily() string {
	if x != nil {
		return x.ForceIpFamily
	}
	return ""
}

func (x *ForwardEchoRequest) GetHbone() *HBONE {
	if x != nil {
		return x.Hbone
	}
	return nil
}

func (x *ForwardEchoRequest) GetDoubleHbone() *HBONE {
	if x != nil {
		return x.DoubleHbone
	}
	return nil
}

func (x *ForwardEchoRequest) GetProxyProtocolVersion() ProxyProtoVersion {
	if x != nil {
		return x.ProxyProtocolVersion
	}
	return ProxyProtoVersion_NONE
}

type HBONE struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Headers []*Header              `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// If non-empty, make the request with the corresponding cert and key.
	Cert string `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// If non-empty, verify the server CA
	CaCert string `protobuf:"bytes,4,opt,name=caCert,proto3" json:"caCert,omitempty"`
	// If non-empty, make the request with the corresponding cert and key file.
	CertFile string `protobuf:"bytes,5,opt,name=certFile,proto3" json:"certFile,omitempty"`
	KeyFile  string `protobuf:"bytes,6,opt,name=keyFile,proto3" json:"keyFile,omitempty"`
	// If non-empty, verify the server CA with the ca cert file.
	CaCertFile string `protobuf:"bytes,7,opt,name=caCertFile,proto3" json:"caCertFile,omitempty"`
	// Skip verifying peer's certificate.
	InsecureSkipVerify bool `protobuf:"varint,8,opt,name=insecureSkipVerify,proto3" json:"insecureSkipVerify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HBONE) Reset() {
	*x = HBONE{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HBONE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HBONE) ProtoMessage() {}

func (x *HBONE) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HBONE.ProtoReflect.Descriptor instead.
func (*HBONE) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{4}
}

func (x *HBONE) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HBONE) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HBONE) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *HBONE) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HBONE) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *HBONE) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *HBONE) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *HBONE) GetCaCertFile() string {
	if x != nil {
		return x.CaCertFile
	}
	return ""
}

func (x *HBONE) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type Alpn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alpn) Reset() {
	*x = Alpn{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alpn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alpn) ProtoMessage() {}

func (x *Alpn) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alpn.ProtoReflect.Descriptor instead.
func (*Alpn) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{5}
}

func (x *Alpn) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type ForwardEchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardEchoResponse) Reset() {
	*x = ForwardEchoResponse{}
	mi := &file_test_echo_proto_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEchoResponse) ProtoMessage() {}

func (x *ForwardEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_echo_proto_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEchoResponse.ProtoReflect.Descriptor instead.
func (*ForwardEchoResponse) Descriptor() ([]byte, []int) {
	return file_test_echo_proto_echo_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardEchoResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_test_echo_proto_echo_proto protoreflect.FileDescriptor

const file_test_echo_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x1atest/echo/proto/echo.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc4\a\n" +
	"\x12ForwardEchoRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x10\n" +
	"\x03qps\x18\x02 \x01(\x05R\x03qps\x12%\n" +
	"\x0etimeout_micros\x18\x03 \x01(\x03R\rtimeoutMicros\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12'\n" +
	"\aheaders\x18\x05 \x03(\v2\r.proto.HeaderR\aheaders\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x16\n" +
	"\x06method\x18\t \x01(\tR\x06method\x12\x14\n" +
	"\x05http2\x18\a \x01(\bR\x05http2\x12\x14\n" +
	"\x05http3\x18\x0f \x01(\bR\x05http3\x12 \n" +
	"\vserverFirst\x18\b \x01(\bR\vserverFirst\x12(\n" +
	"\x0ffollowRedirects\x18\x0e \x01(\bR\x0ffollowRedirects\x12\x12\n" +
	"\x04cert\x18\n" +
	" \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\v \x01(\tR\x03key\x12\x16\n" +
	"\x06caCert\x18\f \x01(\tR\x06caCert\x12\x1a\n" +
	"\bcertFile\x18\x10 \x01(\tR\bcertFile\x12\x18\n" +
	"\akeyFile\x18\x11 \x01(\tR\akeyFile\x12\x1e\n" +
	"\n" +
	"caCertFile\x18\x12 \x01(\tR\n" +
	"caCertFile\x12.\n" +
	"\x12insecureSkipVerify\x18\x13 \x01(\bR\x12insecureSkipVerify\x12\x1f\n" +
	"\x04alpn\x18\r \x01(\v2\v.proto.AlpnR\x04alpn\x12\x1e\n" +
	"\n" +
	"serverName\x18\x14 \x01(\tR\n" +
	"serverName\x12H\n" +
	"\x10expectedResponse\x18\x15 \x01(\v2\x1c.google.protobuf.StringValueR\x10expectedResponse\x128\n" +
	"\x17newConnectionPerRequest\x18\x16 \x01(\bR\x17newConnectionPerRequest\x12&\n" +
	"\x0eforceDNSLookup\x18\x17 \x01(\bR\x0eforceDNSLookup\x12&\n" +
	"\x0fforce_ip_family\x18\x1a \x01(\tR\rforceIpFamily\x12\"\n" +
	"\x05hbone\x18\x18 \x01(\v2\f.proto.HBONER\x05hbone\x12/\n" +
	"\fdouble_hbone\x18\x1b \x01(\v2\f.proto.HBONER\vdoubleHbone\x12L\n" +
	"\x14proxyProtocolVersion\x18\x19 \x01(\x0e2\x18.proto.ProxyProtoVersionR\x14proxyProtocolVersion\"\x8e\x02\n" +
	"\x05HBONE\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12'\n" +
	"\aheaders\x18\x01 \x03(\v2\r.proto.HeaderR\aheaders\x12\x12\n" +
	"\x04cert\x18\x02 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06caCert\x18\x04 \x01(\tR\x06caCert\x12\x1a\n" +
	"\bcertFile\x18\x05 \x01(\tR\bcertFile\x12\x18\n" +
	"\akeyFile\x18\x06 \x01(\tR\akeyFile\x12\x1e\n" +
	"\n" +
	"caCertFile\x18\a \x01(\tR\n" +
	"caCertFile\x12.\n" +
	"\x12insecureSkipVerify\x18\b \x01(\bR\x12insecureSkipVerify\"\x1c\n" +
	"\x04Alpn\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\"-\n" +
	"\x13ForwardEchoResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output*-\n" +
	"\x11ProxyProtoVersion\x12\b\n" +
	"\x04NONE\x10\x00\x12\x06\n" +
	"\x02V1\x10\x01\x12\x06\n" +
	"\x02V2\x10\x022\x88\x01\n" +
	"\x0fEchoTestService\x12/\n" +
	"\x04Echo\x12\x12.proto.EchoRequest\x1a\x13.proto.EchoResponse\x12D\n" +
	"\vForwardEcho\x12\x19.proto.ForwardEchoRequest\x1a\x1a.proto.ForwardEchoResponseB\x1f\n" +
	"\rio.istio.testB\x04EchoZ\b../protob\x06proto3"

var (
	file_test_echo_proto_echo_proto_rawDescOnce sync.Once
	file_test_echo_proto_echo_proto_rawDescData []byte
)

func file_test_echo_proto_echo_proto_rawDescGZIP() []byte {
	file_test_echo_proto_echo_proto_rawDescOnce.Do(func() {
		file_test_echo_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_echo_proto_echo_proto_rawDesc), len(file_test_echo_proto_echo_proto_rawDesc)))
	})
	return file_test_echo_proto_echo_proto_rawDescData
}

var file_test_echo_proto_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_echo_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_test_echo_proto_echo_proto_goTypes = []any{
	(ProxyProtoVersion)(0),         // 0: proto.ProxyProtoVersion
	(*EchoRequest)(nil),            // 1: proto.EchoRequest
	(*EchoResponse)(nil),           // 2: proto.EchoResponse
	(*Header)(nil),                 // 3: proto.Header
	(*ForwardEchoRequest)(nil),     // 4: proto.ForwardEchoRequest
	(*HBONE)(nil),                  // 5: proto.HBONE
	(*Alpn)(nil),                   // 6: proto.Alpn
	(*ForwardEchoResponse)(nil),    // 7: proto.ForwardEchoResponse
	(*wrapperspb.StringValue)(nil), // 8: google.protobuf.StringValue
}
var file_test_echo_proto_echo_proto_depIdxs = []int32{
	3, // 0: proto.ForwardEchoRequest.headers:type_name -> proto.Header
	6, // 1: proto.ForwardEchoRequest.alpn:type_name -> proto.Alpn
	8, // 2: proto.ForwardEchoRequest.expectedResponse:type_name -> google.protobuf.StringValue
	5, // 3: proto.ForwardEchoRequest.hbone:type_name -> proto.HBONE
	5, // 4: proto.ForwardEchoRequest.double_hbone:type_name -> proto.HBONE
	0, // 5: proto.ForwardEchoRequest.proxyProtocolVersion:type_name -> proto.ProxyProtoVersion
	3, // 6: proto.HBONE.headers:type_name -> proto.Header
	1, // 7: proto.EchoTestService.Echo:input_type -> proto.EchoRequest
	4, // 8: proto.EchoTestService.ForwardEcho:input_type -> proto.ForwardEchoRequest
	2, // 9: proto.EchoTestService.Echo:output_type -> proto.EchoResponse
	7, // 10: proto.EchoTestService.ForwardEcho:output_type -> proto.ForwardEchoResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_test_echo_proto_echo_proto_init() }
func file_test_echo_proto_echo_proto_init() {
	if File_test_echo_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_echo_proto_echo_proto_rawDesc), len(file_test_echo_proto_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_echo_proto_echo_proto_goTypes,
		DependencyIndexes: file_test_echo_proto_echo_proto_depIdxs,
		EnumInfos:         file_test_echo_proto_echo_proto_enumTypes,
		MessageInfos:      file_test_echo_proto_echo_proto_msgTypes,
	}.Build()
	File_test_echo_proto_echo_proto = out.File
	file_test_echo_proto_echo_proto_goTypes = nil
	file_test_echo_proto_echo_proto_depIdxs = nil
}
