package(default_visibility = ["//tools/codegen/pkg/bootstrapgen:__pkg__"])

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["bootstrapTemplate.go"],
)
