filegroup(
    name = "input",
    srcs = [
        "route-rule-101.yaml",
        "route-rule-100-delay-7s.yaml",
        "route-rule-100-delay-700s.yaml",
        "route-rule-100-delay-invalid.yaml",
        "mixer-rule-ratings-ratelimit-5per_s.yaml",
        "mixer-rule-ratings-ratelimit-invalid.yaml",
    ],
    visibility = ["//visibility:public"],
)
