# Add aliases for envoy specific targets so that the docker build
# targets are consistent for all istio repos, e.g. //docker:<image>
alias(
    name = "proxy",
    actual = "//src/envoy/mixer:proxy",
)

alias(
    name = "proxy_debug",
    actual = "//src/envoy/mixer:proxy_debug",
)
