# Add aliases for envoy specific targets so that the docker build
# targets are consistent for all istio repos, e.g. //docker:<image>
alias(
    name = "envoy",
    actual = "//src/envoy/mixer:envoy_image",
)

alias(
    name = "envoy_debug",
    actual = "//src/envoy/mixer:envoy_image_debug",
)
