FROM alpine:3.8 as go_generate_dependency_builder
RUN apk add --update --upgrade --no-cache \
    build-base \
    git \
    go>1.10

ENV GOPATH=/go \
    PATH=/go/bin/:$PATH
RUN go get -u -v \
    github.com/jteeuwen/go-bindata/... \
    github.com/maxbrunsfeld/counterfeiter

ENTRYPOINT ["counterfeiter"]

