load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["diff.go"],
    visibility = ["//visibility:public"],
    deps = ["@com_github_pmezard_go_difflib//difflib:go_default_library"],
)
