{
 "title": "Basic Mesh Dashboard",
 "description": "Dashboard based directly on Envoy metrics",
 "tags": [ "basic" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Mesh Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{app!=\"istio-ingressgateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ingress Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{app=\"istio-ingressgateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "description": "Non-5xx responses",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",response_code_class!=\"5xx\"}[1m])) / sum(rate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",response_code_class=\"4xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",response_code_class=\"5xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Server View (HTTP/GRPC)",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_join(label_join(sum(irate(envoy_http_downstream_rq[1m])) by (app, version, namespace), \"_tmp_destination_workload_var\", \".\", \"app\", \"namespace\"), \"destination_workload_var\", \"/\", \"_tmp_destination_workload_var\", \"version\")"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, app, version, namespace))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, app, version, namespace))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket[1m])) by (le, app, version, namespace))"
    },
    {
     "expr": "(sum(irate(envoy_http_downstream_rq[1m])) by (app, version, namespace) - sum(irate(envoy_http_downstream_rq{response_code_class=\"5xx\"}[1m])) by (app, version, namespace))/sum(irate(envoy_http_downstream_rq[1m])) by (app, version, namespace)"
    }
   ]
  },
  {
   "title": "Client View (HTTP/GRPC)",
   "type": "table",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(label_join(label_join(sum(irate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\"}[1m])) by (cluster_name, app, version, namespace), \"_tmp_source_workload_var\", \".\", \"app\", \"namespace\"), \"_source_workload_var\", \"/\", \"_tmp_source_workload_var\", \"version\"), \"service_name_var\", \"$4.$5/$3\", \"cluster_name\", \"(.*?)\\\\|(.*?)\\\\|(.*?)\\\\|(.*?)\\\\.(.*?)\\\\.(.*)\")"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\"}[1m])) by (le, cluster_name, app, version, namespace))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\"}[1m])) by (le, cluster_name, app, version, namespace))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\"}[1m])) by (le, cluster_name, app, version, namespace))"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\",response_code_class=~\"(2|3|4)xx\"}[1m])) by (cluster_name, app, version, namespace) / sum(irate(envoy_cluster_upstream_rq{cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\"}[1m])) by (cluster_name, app, version, namespace) "
    }
   ]
  },
  {
   "title": "Ingress Outbound P99 Latency",
   "type": "graph",
   "gridPos": { "h": 16, "w": 21, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"istio-ingressgateway\", cluster_name=~\"outbound.*\",cluster_name!~\".*istio-system.*\",cluster_name!~\".*prometheus.*\"}[1m])) by (le, cluster_name, app, version, namespace)),\"service_name_var\", \"$4.$5/$3\", \"cluster_name\", \"(.*?)\\\\|(.*?)\\\\|(.*?)\\\\|(.*?)\\\\.(.*?)\\\\.(.*)\")",
     "legendFormat": "{{ service_name_var }}"
    }
   ]
  }
 ]
}