package(default_visibility = ["//pkg:__subpackages__"])

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "catalog.go",
        "service.go",
        "serviceBinding.go",
        "serviceInstance.go",
        "servicePlan.go",
    ],
)
