load("@org_pubref_rules_protobuf//gogo:rules.bzl", "gogo_proto_library")

gogo_proto_library(
    name = "go_default_library",
    protos = [
        "config.proto",
    ],
    verbose = 0,
    visibility = ["//adapter/stdioLogger:__pkg__"],
)
