# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest
FROM gcr.io/istio-release/base:${BASE_VERSION}
USER 1000:1000
ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/istioctl /usr/local/bin/istioctl
ENTRYPOINT ["/usr/local/bin/istioctl"]
