# Change this and ../../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy:151ea7534cb8c1f9e25ba315b8d95ba0c57939a2
ADD pilot-agent /usr/local/bin/pilot-agent

COPY envoy_pilot.json      /etc/istio/proxy/envoy_pilot.json
COPY envoy_pilot_auth.json /etc/istio/proxy/envoy_pilot_auth.json
COPY envoy_mixer.json      /etc/istio/proxy/envoy_mixer.json
COPY envoy_mixer_auth.json /etc/istio/proxy/envoy_mixer_auth.json

ENTRYPOINT ["/usr/local/bin/pilot-agent"]
