# keep Dockerfile.proxy and Dockerfile.proxy_debug consistent for proxy sha
FROM gcr.io/istio-testing/envoy:8b47ad625b2b8762513a206c8896e49f00032450
ADD pilot-agent /usr/local/bin/pilot-agent

COPY envoy_pilot.json      /etc/istio/proxy/envoy_pilot.json
COPY envoy_pilot_auth.json /etc/istio/proxy/envoy_pilot_auth.json
COPY envoy_mixer.json      /etc/istio/proxy/envoy_mixer.json
COPY envoy_mixer_auth.json /etc/istio/proxy/envoy_mixer_auth.json

ENTRYPOINT ["/usr/local/bin/pilot-agent"]
