ARG ISTIO_BIN=.
# This is used for internal Eureka testing. Mirrors k8s endpoint instances to an Eureka server.
FROM scratch
ADD ${ISTIO_BIN}/pilot-test-eurekamirror /usr/local/bin/eurekamirror
ENTRYPOINT ["/usr/local/bin/eurekamirror"]
