# Change this and ../../WORKSPACE at the same time
FROM gcr.io/istio-testing/envoy-debug:f1b698b1c35d2a5433e0675e5e762171e15c64b3
ADD pilot-agent /usr/local/bin/pilot-agent

COPY envoy_pilot.json      /etc/istio/proxy/envoy_pilot.json
COPY envoy_pilot_auth.json /etc/istio/proxy/envoy_pilot_auth.json
COPY envoy_mixer.json      /etc/istio/proxy/envoy_mixer.json
COPY envoy_mixer_auth.json /etc/istio/proxy/envoy_mixer_auth.json

ENTRYPOINT ["/usr/local/bin/pilot-agent"]
