// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networking/v1alpha3/destination_rule.proto

/*
Package v1alpha3 is a generated protocol buffer package.

It is generated from these files:
	networking/v1alpha3/destination_rule.proto
	networking/v1alpha3/external_service.proto
	networking/v1alpha3/gateway.proto
	networking/v1alpha3/virtual_service.proto

It has these top-level messages:
	DestinationRule
	TrafficPolicy
	Subset
	LoadBalancerSettings
	ConnectionPoolSettings
	OutlierDetection
	TLSSettings
	ExternalService
	Gateway
	Server
	Port
	VirtualService
	Destination
	HTTPRoute
	TCPRoute
	HTTPMatchRequest
	DestinationWeight
	L4MatchAttributes
	HTTPRedirect
	HTTPRewrite
	StringMatch
	HTTPRetry
	CorsPolicy
	HTTPFaultInjection
	PortSelector
*/
package v1alpha3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Standard load balancing algorithms that require no tuning.
type LoadBalancerSettings_SimpleLB int32

const (
	// Round Robin policy. Default
	LoadBalancerSettings_ROUND_ROBIN LoadBalancerSettings_SimpleLB = 0
	// The least request load balancer uses an O(1) algorithm which selects
	// two random healthy hosts and picks the host which has fewer active
	// requests.
	LoadBalancerSettings_LEAST_CONN LoadBalancerSettings_SimpleLB = 1
	// The random load balancer selects a random healthy host. The random
	// load balancer generally performs better than round robin if no health
	// checking policy is configured.
	LoadBalancerSettings_RANDOM LoadBalancerSettings_SimpleLB = 2
	// This option will forward the connection to the original IP address
	// requested by the caller without doing any form of load
	// balancing. This option must be used with care. It is meant for
	// advanced use cases. Refer to Original Destination load balancer in
	// Envoy for further details.
	LoadBalancerSettings_PASSTHROUGH LoadBalancerSettings_SimpleLB = 3
)

var LoadBalancerSettings_SimpleLB_name = map[int32]string{
	0: "ROUND_ROBIN",
	1: "LEAST_CONN",
	2: "RANDOM",
	3: "PASSTHROUGH",
}
var LoadBalancerSettings_SimpleLB_value = map[string]int32{
	"ROUND_ROBIN": 0,
	"LEAST_CONN":  1,
	"RANDOM":      2,
	"PASSTHROUGH": 3,
}

func (x LoadBalancerSettings_SimpleLB) String() string {
	return proto.EnumName(LoadBalancerSettings_SimpleLB_name, int32(x))
}
func (LoadBalancerSettings_SimpleLB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

// TLS connection mode
type TLSSettings_TLSmode int32

const (
	// If set to "disable", the proxy will use not setup a TLS connection to the
	// upstream server.
	TLSSettings_DISABLE TLSSettings_TLSmode = 0
	// If set to "simple", the proxy will originate a TLS connection to the
	// upstream server.
	TLSSettings_SIMPLE TLSSettings_TLSmode = 1
	// If set to "mutual", the proxy will secure connections to the
	// upstream using mutual TLS by presenting client certificates for
	// authentication.
	TLSSettings_MUTUAL TLSSettings_TLSmode = 2
)

var TLSSettings_TLSmode_name = map[int32]string{
	0: "DISABLE",
	1: "SIMPLE",
	2: "MUTUAL",
}
var TLSSettings_TLSmode_value = map[string]int32{
	"DISABLE": 0,
	"SIMPLE":  1,
	"MUTUAL":  2,
}

func (x TLSSettings_TLSmode) String() string {
	return proto.EnumName(TLSSettings_TLSmode_name, int32(x))
}
func (TLSSettings_TLSmode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

// DestinationRule defines policies that apply to traffic intended for a
// service after routing has occurred. These rules specify configuration
// for load balancing, connection pool size from the sidecar, and outlier
// detection settings to detect and evict unhealthy hosts from the load
// balancing pool. For example, a simple load balancing policy for the
// ratings service would look as follows:
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       name: ratings
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//
// Version specific policies can be specified by defining a named
// subset and overriding the settings specified at the service level. The
// following rule uses a round robin load balancing policy for all traffic
// going to a subset named testversion that is composed of endpoints (e.g.,
// pods) with labels (version:v3).
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       name: ratings
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//       subsets:
//       - name: testversion
//         labels:
//           version: v3
//         trafficPolicy:
//           loadBalancer:
//             simple: ROUND_ROBIN
//
// Note that policies specified for subsets will not take effect until
// a route rule explicitly sends traffic to this subset.
type DestinationRule struct {
	// REQUIRED. The destination address for traffic captured by this
	// rule.  Could be a DNS name with wildcard prefix or a CIDR
	// prefix. Depending on the platform, short-names can also be used
	// instead of a FQDN (i.e. has no dots in the name). In such a scenario,
	// the FQDN of the host would be derived based on the underlying
	// platform.
	//
	// For example on Kubernetes, when hosts contains a short name, Istio
	// will interpret the short name based on the namespace of the client
	// where rules are being applied. Thus, when a client in the "default"
	// namespace applies a rule containing a name "reviews", Istio will setup
	// routes to the "reviews.default.svc.cluster.local" service. However, if
	// a different name such as "reviews.sales" is used, it would be treated
	// as a FQDN during virtual host matching.  In Consul, a plain service
	// name would be resolved to the FQDN "reviews.service.consul".
	//
	// Note that the hosts field applies to both HTTP and TCP
	// services. Service inside the mesh, i.e. those found in the service
	// registry, must always be referred to using their alphanumeric
	// names. IP addresses or CIDR prefixes are allowed only for services
	// defined via the Gateway.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Traffic policies to apply (load balancing policy, connection pool
	// sizes, outlier detection).
	TrafficPolicy *TrafficPolicy `protobuf:"bytes,2,opt,name=traffic_policy,json=trafficPolicy" json:"traffic_policy,omitempty"`
	// One or more named sets that represent individual versions of a
	// service. Traffic policies can be overridden at subset level.
	Subsets []*Subset `protobuf:"bytes,3,rep,name=subsets" json:"subsets,omitempty"`
}

func (m *DestinationRule) Reset()                    { *m = DestinationRule{} }
func (m *DestinationRule) String() string            { return proto.CompactTextString(m) }
func (*DestinationRule) ProtoMessage()               {}
func (*DestinationRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DestinationRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DestinationRule) GetTrafficPolicy() *TrafficPolicy {
	if m != nil {
		return m.TrafficPolicy
	}
	return nil
}

func (m *DestinationRule) GetSubsets() []*Subset {
	if m != nil {
		return m.Subsets
	}
	return nil
}

// Traffic policies to apply for a specific destination. See
// DestinationRule for examples.
type TrafficPolicy struct {
	// Settings controlling the load balancer algorithms.
	LoadBalancer *LoadBalancerSettings `protobuf:"bytes,1,opt,name=load_balancer,json=loadBalancer" json:"load_balancer,omitempty"`
	// Settings controlling the volume of connections to an upstream service
	ConnectionPool *ConnectionPoolSettings `protobuf:"bytes,2,opt,name=connection_pool,json=connectionPool" json:"connection_pool,omitempty"`
	// Settings controlling eviction of unhealthy hosts from the load balancing pool
	OutlierDetection *OutlierDetection `protobuf:"bytes,3,opt,name=outlier_detection,json=outlierDetection" json:"outlier_detection,omitempty"`
	// TLS related settings for connections to the upstream service.
	Tls *TLSSettings `protobuf:"bytes,4,opt,name=tls" json:"tls,omitempty"`
}

func (m *TrafficPolicy) Reset()                    { *m = TrafficPolicy{} }
func (m *TrafficPolicy) String() string            { return proto.CompactTextString(m) }
func (*TrafficPolicy) ProtoMessage()               {}
func (*TrafficPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TrafficPolicy) GetLoadBalancer() *LoadBalancerSettings {
	if m != nil {
		return m.LoadBalancer
	}
	return nil
}

func (m *TrafficPolicy) GetConnectionPool() *ConnectionPoolSettings {
	if m != nil {
		return m.ConnectionPool
	}
	return nil
}

func (m *TrafficPolicy) GetOutlierDetection() *OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *TrafficPolicy) GetTls() *TLSSettings {
	if m != nil {
		return m.Tls
	}
	return nil
}

// A subset of endpoints of a service. Subsets can be used for scenarios
// like A/B testing, or routing to a specific version of a service. Refer
// to VirtualService documentation for examples of using subsets in these
// scenarios. In addition, traffic policies defined at the service-level
// can be overridden at a subset-level. The following rule uses a round
// robin load balancing policy for all traffic going to a subset named
// testversion that is composed of endpoints (e.g., pods) with labels
// (version:v3).
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       name: ratings
//       trafficPolicy:
//         loadBalancer:
//           simple: LEAST_CONN
//       subsets:
//       - name: testversion
//         labels:
//           version: v3
//         trafficPolicy:
//           loadBalancer:
//             simple: ROUND_ROBIN
//
// Note that policies specified for subsets will not take effect until
// a route rule explicitly sends traffic to this subset.
type Subset struct {
	// REQUIRED. name of the subset. The service name and the subset name can
	// be used for traffic splitting in a route rule.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// REQUIRED. Labels apply a filter over the endpoints of a service in the
	// service registry. See route rules for examples of usage.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Traffic policies that apply to this subset. Subsets inherit the
	// traffic policies specified at the DestinationRule level. Settings
	// specified at the subset level will override the corresponding settings
	// specified at the DestinationRule level.
	TrafficPolicy *TrafficPolicy `protobuf:"bytes,3,opt,name=traffic_policy,json=trafficPolicy" json:"traffic_policy,omitempty"`
}

func (m *Subset) Reset()                    { *m = Subset{} }
func (m *Subset) String() string            { return proto.CompactTextString(m) }
func (*Subset) ProtoMessage()               {}
func (*Subset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Subset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Subset) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Subset) GetTrafficPolicy() *TrafficPolicy {
	if m != nil {
		return m.TrafficPolicy
	}
	return nil
}

// Load balancing policies to apply for a specific destination. See Envoy's
// load balancing
// [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing.html)
// for more details.
//
// For example, the following rule uses a round robin load balancing policy
// for all traffic going to the ratings service.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       name: ratings
//       trafficPolicy:
//         loadBalancer:
//           simple: ROUND_ROBIN
//
// The following example uses the consistent hashing based load balancer
// for the same ratings service using the Cookie header as the hash key.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-ratings
//     spec:
//       name: ratings
//       trafficPolicy:
//         loadBalancer:
//           consistentHash:
//             http_header: Cookie
//
type LoadBalancerSettings struct {
	// Upstream load balancing policy.
	//
	// Types that are valid to be assigned to LbPolicy:
	//	*LoadBalancerSettings_Simple
	//	*LoadBalancerSettings_ConsistentHash
	LbPolicy isLoadBalancerSettings_LbPolicy `protobuf_oneof:"lb_policy"`
}

func (m *LoadBalancerSettings) Reset()                    { *m = LoadBalancerSettings{} }
func (m *LoadBalancerSettings) String() string            { return proto.CompactTextString(m) }
func (*LoadBalancerSettings) ProtoMessage()               {}
func (*LoadBalancerSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isLoadBalancerSettings_LbPolicy interface{ isLoadBalancerSettings_LbPolicy() }

type LoadBalancerSettings_Simple struct {
	Simple LoadBalancerSettings_SimpleLB `protobuf:"varint,1,opt,name=simple,enum=istio.networking.v1alpha3.LoadBalancerSettings_SimpleLB,oneof"`
}
type LoadBalancerSettings_ConsistentHash struct {
	ConsistentHash *LoadBalancerSettings_ConsistentHashLB `protobuf:"bytes,2,opt,name=consistent_hash,json=consistentHash,oneof"`
}

func (*LoadBalancerSettings_Simple) isLoadBalancerSettings_LbPolicy()         {}
func (*LoadBalancerSettings_ConsistentHash) isLoadBalancerSettings_LbPolicy() {}

func (m *LoadBalancerSettings) GetLbPolicy() isLoadBalancerSettings_LbPolicy {
	if m != nil {
		return m.LbPolicy
	}
	return nil
}

func (m *LoadBalancerSettings) GetSimple() LoadBalancerSettings_SimpleLB {
	if x, ok := m.GetLbPolicy().(*LoadBalancerSettings_Simple); ok {
		return x.Simple
	}
	return LoadBalancerSettings_ROUND_ROBIN
}

func (m *LoadBalancerSettings) GetConsistentHash() *LoadBalancerSettings_ConsistentHashLB {
	if x, ok := m.GetLbPolicy().(*LoadBalancerSettings_ConsistentHash); ok {
		return x.ConsistentHash
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LoadBalancerSettings) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LoadBalancerSettings_OneofMarshaler, _LoadBalancerSettings_OneofUnmarshaler, _LoadBalancerSettings_OneofSizer, []interface{}{
		(*LoadBalancerSettings_Simple)(nil),
		(*LoadBalancerSettings_ConsistentHash)(nil),
	}
}

func _LoadBalancerSettings_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LoadBalancerSettings)
	// lb_policy
	switch x := m.LbPolicy.(type) {
	case *LoadBalancerSettings_Simple:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Simple))
	case *LoadBalancerSettings_ConsistentHash:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConsistentHash); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LoadBalancerSettings.LbPolicy has unexpected type %T", x)
	}
	return nil
}

func _LoadBalancerSettings_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LoadBalancerSettings)
	switch tag {
	case 1: // lb_policy.simple
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.LbPolicy = &LoadBalancerSettings_Simple{LoadBalancerSettings_SimpleLB(x)}
		return true, err
	case 2: // lb_policy.consistent_hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoadBalancerSettings_ConsistentHashLB)
		err := b.DecodeMessage(msg)
		m.LbPolicy = &LoadBalancerSettings_ConsistentHash{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LoadBalancerSettings_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LoadBalancerSettings)
	// lb_policy
	switch x := m.LbPolicy.(type) {
	case *LoadBalancerSettings_Simple:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Simple))
	case *LoadBalancerSettings_ConsistentHash:
		s := proto.Size(x.ConsistentHash)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Consistent hashing (ketama hash) based load balancer for even load
// distribution/redistribution when the connection pool changes. This
// load balancing policy is applicable only for HTTP-based
// connections. A user specified HTTP header is used as the key with
// [xxHash](http://cyan4973.github.io/xxHash) hashing.
type LoadBalancerSettings_ConsistentHashLB struct {
	// REQUIRED. The name of the HTTP request header that will be used to
	// obtain the hash key. If the request header is not present, the load
	// balancer will use a random number as the hash, effectively making
	// the load balancing policy random.
	HttpHeader string `protobuf:"bytes,1,opt,name=http_header,json=httpHeader" json:"http_header,omitempty"`
	// The minimum number of virtual nodes to use for the hash
	// ring. Defaults to 1024. Larger ring sizes result in more granular
	// load distributions. If the number of hosts in the load balancing
	// pool is larger than the ring size, each host will be assigned a
	// single virtual node.
	MinimumRingSize uint32 `protobuf:"varint,2,opt,name=minimum_ring_size,json=minimumRingSize" json:"minimum_ring_size,omitempty"`
}

func (m *LoadBalancerSettings_ConsistentHashLB) Reset()         { *m = LoadBalancerSettings_ConsistentHashLB{} }
func (m *LoadBalancerSettings_ConsistentHashLB) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerSettings_ConsistentHashLB) ProtoMessage()    {}
func (*LoadBalancerSettings_ConsistentHashLB) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

func (m *LoadBalancerSettings_ConsistentHashLB) GetHttpHeader() string {
	if m != nil {
		return m.HttpHeader
	}
	return ""
}

func (m *LoadBalancerSettings_ConsistentHashLB) GetMinimumRingSize() uint32 {
	if m != nil {
		return m.MinimumRingSize
	}
	return 0
}

// Connection pool settings for an upstream host. The settings apply to
// each individual host in the upstream service.  See Envoy's [circuit
// breaker](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking)
// for more details. Connection pool settings can be applied at the TCP
// level as well as at HTTP level.
//
// For example, the following rule sets a limit of 100 connections to redis
// service called myredissrv with a connect timeout of 30ms
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: bookinfo-redis
//     spec:
//       destination:
//         name: myredissrv
//       trafficPolicy:
//         connectionPool:
//           tcp:
//             maxConnections: 100
//             connectTimeout: 30ms
//
type ConnectionPoolSettings struct {
	// Settings common to both HTTP and TCP upstream connections.
	Tcp *ConnectionPoolSettings_TCPSettings `protobuf:"bytes,1,opt,name=tcp" json:"tcp,omitempty"`
	// HTTP connection pool settings.
	Http *ConnectionPoolSettings_HTTPSettings `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *ConnectionPoolSettings) Reset()                    { *m = ConnectionPoolSettings{} }
func (m *ConnectionPoolSettings) String() string            { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings) ProtoMessage()               {}
func (*ConnectionPoolSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConnectionPoolSettings) GetTcp() *ConnectionPoolSettings_TCPSettings {
	if m != nil {
		return m.Tcp
	}
	return nil
}

func (m *ConnectionPoolSettings) GetHttp() *ConnectionPoolSettings_HTTPSettings {
	if m != nil {
		return m.Http
	}
	return nil
}

// Settings common to both HTTP and TCP upstream connections.
type ConnectionPoolSettings_TCPSettings struct {
	// Maximum number of HTTP1 /TCP connections to a destination host.
	MaxConnections int32 `protobuf:"varint,1,opt,name=max_connections,json=maxConnections" json:"max_connections,omitempty"`
	// TCP connection timeout.
	ConnectTimeout *google_protobuf.Duration `protobuf:"bytes,2,opt,name=connect_timeout,json=connectTimeout" json:"connect_timeout,omitempty"`
}

func (m *ConnectionPoolSettings_TCPSettings) Reset()         { *m = ConnectionPoolSettings_TCPSettings{} }
func (m *ConnectionPoolSettings_TCPSettings) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings_TCPSettings) ProtoMessage()    {}
func (*ConnectionPoolSettings_TCPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *ConnectionPoolSettings_TCPSettings) GetMaxConnections() int32 {
	if m != nil {
		return m.MaxConnections
	}
	return 0
}

func (m *ConnectionPoolSettings_TCPSettings) GetConnectTimeout() *google_protobuf.Duration {
	if m != nil {
		return m.ConnectTimeout
	}
	return nil
}

// Settings applicable to HTTP1.1/HTTP2/GRPC connections.
type ConnectionPoolSettings_HTTPSettings struct {
	// Maximum number of pending HTTP requests to a destination. Default 1024.
	Http1MaxPendingRequests int32 `protobuf:"varint,1,opt,name=http1_max_pending_requests,json=http1MaxPendingRequests" json:"http1_max_pending_requests,omitempty"`
	// Maximum number of requests to a backend. Default 1024.
	Http2MaxRequests int32 `protobuf:"varint,2,opt,name=http2_max_requests,json=http2MaxRequests" json:"http2_max_requests,omitempty"`
	// Maximum number of requests per connection to a backend. Setting this
	// parameter to 1 disables keep alive.
	MaxRequestsPerConnection int32 `protobuf:"varint,3,opt,name=max_requests_per_connection,json=maxRequestsPerConnection" json:"max_requests_per_connection,omitempty"`
	// Maximum number of retries that can be outstanding to all hosts in a
	// cluster at a given time. Defaults to 3.
	MaxRetries int32 `protobuf:"varint,4,opt,name=max_retries,json=maxRetries" json:"max_retries,omitempty"`
}

func (m *ConnectionPoolSettings_HTTPSettings) Reset()         { *m = ConnectionPoolSettings_HTTPSettings{} }
func (m *ConnectionPoolSettings_HTTPSettings) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolSettings_HTTPSettings) ProtoMessage()    {}
func (*ConnectionPoolSettings_HTTPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 1}
}

func (m *ConnectionPoolSettings_HTTPSettings) GetHttp1MaxPendingRequests() int32 {
	if m != nil {
		return m.Http1MaxPendingRequests
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetHttp2MaxRequests() int32 {
	if m != nil {
		return m.Http2MaxRequests
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetMaxRequestsPerConnection() int32 {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return 0
}

func (m *ConnectionPoolSettings_HTTPSettings) GetMaxRetries() int32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

// A Circuit breaker implementation that tracks the status of each
// individual host in the upstream service.  While currently applicable to
// only HTTP services, future versions will support opaque TCP services as
// well. For HTTP services, hosts that continually return errors for API
// calls are ejected from the pool for a pre-defined period of time. See
// Envoy's [outlier
// detection](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/outlier)
// for more details.
//
// The following rule sets a connection pool size of 100 connections and
// 1000 concurrent HTTP2 requests, with no more than 10 req/connection to
// "reviews" service. In addition, it configures upstream hosts to be
// scanned every 5 mins, such that any host that fails 7 consecutive times
// with 5XX error code will be ejected for 15 minutes.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: reviews-cb-policy
//     spec:
//       destination:
//         name: reviews
//       trafficPolicy:
//         connectionPool:
//           tcp:
//             maxConnections: 100
//           http:
//             http2MaxRequests: 1000
//             maxRequestsPerConnection: 10
//         outlierDetection:
//           http:
//             consecutiveErrors: 7
//             interval: 5m
//             baseEjectionTime: 15m
//
type OutlierDetection struct {
	// Settings for HTTP1.1/HTTP2/GRPC connections.
	Http *OutlierDetection_HTTPSettings `protobuf:"bytes,1,opt,name=http" json:"http,omitempty"`
}

func (m *OutlierDetection) Reset()                    { *m = OutlierDetection{} }
func (m *OutlierDetection) String() string            { return proto.CompactTextString(m) }
func (*OutlierDetection) ProtoMessage()               {}
func (*OutlierDetection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OutlierDetection) GetHttp() *OutlierDetection_HTTPSettings {
	if m != nil {
		return m.Http
	}
	return nil
}

// Outlier detection settings for HTTP1.1/HTTP2/GRPC connections.
type OutlierDetection_HTTPSettings struct {
	// Number of 5XX errors before a host is ejected from the connection
	// pool. Defaults to 5.
	ConsecutiveErrors int32 `protobuf:"varint,1,opt,name=consecutive_errors,json=consecutiveErrors" json:"consecutive_errors,omitempty"`
	// Time interval between ejection sweep analysis. format:
	// 1h/1m/1s/1ms. MUST BE >=1ms. Default is 10s.
	Interval *google_protobuf.Duration `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
	// Minimum ejection duration. A host will remain ejected for a period
	// equal to the product of minimum ejection duration and the number of
	// times the host has been ejected. This technique allows the system to
	// automatically increase the ejection period for unhealthy upstream
	// servers. format: 1h/1m/1s/1ms. MUST BE >=1ms. Default is 30s.
	BaseEjectionTime *google_protobuf.Duration `protobuf:"bytes,3,opt,name=base_ejection_time,json=baseEjectionTime" json:"base_ejection_time,omitempty"`
	// Maximum % of hosts in the load balancing pool for the upstream
	// service that can be ejected. Defaults to 10%.
	MaxEjectionPercent int32 `protobuf:"varint,4,opt,name=max_ejection_percent,json=maxEjectionPercent" json:"max_ejection_percent,omitempty"`
}

func (m *OutlierDetection_HTTPSettings) Reset()         { *m = OutlierDetection_HTTPSettings{} }
func (m *OutlierDetection_HTTPSettings) String() string { return proto.CompactTextString(m) }
func (*OutlierDetection_HTTPSettings) ProtoMessage()    {}
func (*OutlierDetection_HTTPSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *OutlierDetection_HTTPSettings) GetConsecutiveErrors() int32 {
	if m != nil {
		return m.ConsecutiveErrors
	}
	return 0
}

func (m *OutlierDetection_HTTPSettings) GetInterval() *google_protobuf.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *OutlierDetection_HTTPSettings) GetBaseEjectionTime() *google_protobuf.Duration {
	if m != nil {
		return m.BaseEjectionTime
	}
	return nil
}

func (m *OutlierDetection_HTTPSettings) GetMaxEjectionPercent() int32 {
	if m != nil {
		return m.MaxEjectionPercent
	}
	return 0
}

// SSL/TLS related settings for upstream connections. See Envoy's [TLS
// context](https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_ssl.html#config-cluster-manager-cluster-ssl)
// for more details. These settings are common to both HTTP and TCP upstreams.
//
// For example, the following rule configures a client to use mutual TLS
// for connections to upstream database cluster.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: db-mtls
//     spec:
//       destination:
//         name: mydbserver
//       tls:
//         mode: MUTUAL
//         clientCertificate: /etc/certs/myclientcert.pem
//         privateKey: /etc/certs/client_private_key.pem
//         caCertificates: /etc/certs/rootcacerts.pem
//
// The following rule configures a client to use TLS when talking to a foreign service whose domain matches *.foo.com.
//
//     apiVersion: networking.istio.io/v1alpha3
//     kind: DestinationRule
//     metadata:
//       name: tls-foo
//     spec:
//       destination:
//         name: *.foo.com
//       tls:
//         mode: SIMPLE
//
type TLSSettings struct {
	// REQUIRED: Indicates whether connections to this port should be secured
	// using TLS. The value of this field determines how TLS is enforced.
	Mode TLSSettings_TLSmode `protobuf:"varint,1,opt,name=mode,enum=istio.networking.v1alpha3.TLSSettings_TLSmode" json:"mode,omitempty"`
	// REQUIRED if mode is "mutual". The path to the file holding the
	// client-side TLS certificate to use.
	ClientCertificate string `protobuf:"bytes,2,opt,name=client_certificate,json=clientCertificate" json:"client_certificate,omitempty"`
	// REQUIRED if mode is "mutual". The path to the file holding the
	// client's private key.
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	// OPTIONAL: The path to the file containing certificate authority
	// certificates to use in verifying a presented server certificate. If
	// omitted, the proxy will not verify the server's certificate.
	CaCertificates string `protobuf:"bytes,4,opt,name=ca_certificates,json=caCertificates" json:"ca_certificates,omitempty"`
	// A list of alternate names to verify the subject identity in the
	// certificate. If specified, the proxy will verify that the server
	// certificate's subject alt name matches one of the specified values.
	SubjectAltNames []string `protobuf:"bytes,5,rep,name=subject_alt_names,json=subjectAltNames" json:"subject_alt_names,omitempty"`
	// SNI string to present to the server during TLS handshake.
	Sni string `protobuf:"bytes,6,opt,name=sni" json:"sni,omitempty"`
}

func (m *TLSSettings) Reset()                    { *m = TLSSettings{} }
func (m *TLSSettings) String() string            { return proto.CompactTextString(m) }
func (*TLSSettings) ProtoMessage()               {}
func (*TLSSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TLSSettings) GetMode() TLSSettings_TLSmode {
	if m != nil {
		return m.Mode
	}
	return TLSSettings_DISABLE
}

func (m *TLSSettings) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *TLSSettings) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *TLSSettings) GetCaCertificates() string {
	if m != nil {
		return m.CaCertificates
	}
	return ""
}

func (m *TLSSettings) GetSubjectAltNames() []string {
	if m != nil {
		return m.SubjectAltNames
	}
	return nil
}

func (m *TLSSettings) GetSni() string {
	if m != nil {
		return m.Sni
	}
	return ""
}

func init() {
	proto.RegisterType((*DestinationRule)(nil), "istio.networking.v1alpha3.DestinationRule")
	proto.RegisterType((*TrafficPolicy)(nil), "istio.networking.v1alpha3.TrafficPolicy")
	proto.RegisterType((*Subset)(nil), "istio.networking.v1alpha3.Subset")
	proto.RegisterType((*LoadBalancerSettings)(nil), "istio.networking.v1alpha3.LoadBalancerSettings")
	proto.RegisterType((*LoadBalancerSettings_ConsistentHashLB)(nil), "istio.networking.v1alpha3.LoadBalancerSettings.ConsistentHashLB")
	proto.RegisterType((*ConnectionPoolSettings)(nil), "istio.networking.v1alpha3.ConnectionPoolSettings")
	proto.RegisterType((*ConnectionPoolSettings_TCPSettings)(nil), "istio.networking.v1alpha3.ConnectionPoolSettings.TCPSettings")
	proto.RegisterType((*ConnectionPoolSettings_HTTPSettings)(nil), "istio.networking.v1alpha3.ConnectionPoolSettings.HTTPSettings")
	proto.RegisterType((*OutlierDetection)(nil), "istio.networking.v1alpha3.OutlierDetection")
	proto.RegisterType((*OutlierDetection_HTTPSettings)(nil), "istio.networking.v1alpha3.OutlierDetection.HTTPSettings")
	proto.RegisterType((*TLSSettings)(nil), "istio.networking.v1alpha3.TLSSettings")
	proto.RegisterEnum("istio.networking.v1alpha3.LoadBalancerSettings_SimpleLB", LoadBalancerSettings_SimpleLB_name, LoadBalancerSettings_SimpleLB_value)
	proto.RegisterEnum("istio.networking.v1alpha3.TLSSettings_TLSmode", TLSSettings_TLSmode_name, TLSSettings_TLSmode_value)
}

func init() { proto.RegisterFile("networking/v1alpha3/destination_rule.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1056 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0x1a, 0x47,
	0x14, 0x0e, 0xac, 0x4d, 0xc2, 0x21, 0x86, 0xf5, 0xc8, 0x6a, 0x09, 0x95, 0x5a, 0x97, 0x8b, 0xd6,
	0x4a, 0x9b, 0xa5, 0x76, 0x54, 0xc9, 0x6d, 0x94, 0xaa, 0x60, 0x50, 0xb0, 0x8a, 0x01, 0x0d, 0x58,
	0xaa, 0x72, 0xb3, 0x1a, 0x96, 0x31, 0x4c, 0xbd, 0x7f, 0xdd, 0x99, 0x75, 0x6d, 0xbf, 0x44, 0xaf,
	0xfa, 0x24, 0xbd, 0xe9, 0x73, 0x54, 0xea, 0x45, 0x9f, 0x22, 0xaf, 0x50, 0xcd, 0x0f, 0xb0, 0xb6,
	0x28, 0xa9, 0xd5, 0xbb, 0xe5, 0x9c, 0xf3, 0x7d, 0x73, 0xe6, 0xfc, 0x7c, 0x03, 0x3c, 0x0f, 0xa9,
	0xf8, 0x25, 0x4a, 0x2e, 0x59, 0x38, 0x6b, 0x5c, 0x1d, 0x12, 0x3f, 0x9e, 0x93, 0x97, 0x8d, 0x29,
	0xe5, 0x82, 0x85, 0x44, 0xb0, 0x28, 0x74, 0x93, 0xd4, 0xa7, 0x4e, 0x9c, 0x44, 0x22, 0x42, 0xcf,
	0x18, 0x17, 0x2c, 0x72, 0x56, 0x08, 0x67, 0x81, 0xa8, 0x7d, 0x3c, 0x8b, 0xa2, 0x99, 0x4f, 0x1b,
	0x2a, 0x70, 0x92, 0x5e, 0x34, 0xa6, 0x69, 0xa2, 0xf0, 0x1a, 0x5a, 0xff, 0x3d, 0x07, 0x95, 0xf6,
	0x8a, 0x15, 0xa7, 0x3e, 0x45, 0x08, 0xb6, 0x42, 0x12, 0xd0, 0x6a, 0x6e, 0x3f, 0x77, 0x50, 0xc4,
	0xea, 0x1b, 0x0d, 0xa0, 0x2c, 0x12, 0x72, 0x71, 0xc1, 0x3c, 0x37, 0x8e, 0x7c, 0xe6, 0xdd, 0x54,
	0xf3, 0xfb, 0xb9, 0x83, 0xd2, 0xd1, 0x81, 0xf3, 0xaf, 0x67, 0x3b, 0x63, 0x0d, 0x18, 0xaa, 0x78,
	0xbc, 0x23, 0xb2, 0x3f, 0xd1, 0x2b, 0x78, 0xcc, 0xd3, 0x09, 0xa7, 0x82, 0x57, 0xad, 0x7d, 0xeb,
	0xa0, 0x74, 0xf4, 0xe9, 0x06, 0xa6, 0x91, 0x8a, 0xc4, 0x0b, 0x44, 0xfd, 0xaf, 0x3c, 0xec, 0xdc,
	0x61, 0x47, 0x63, 0xd8, 0xf1, 0x23, 0x32, 0x75, 0x27, 0xc4, 0x27, 0xa1, 0x47, 0x13, 0x95, 0x7c,
	0xe9, 0xa8, 0xb1, 0x81, 0xb4, 0x17, 0x91, 0x69, 0xcb, 0x84, 0x8f, 0xa8, 0x10, 0x2c, 0x9c, 0x71,
	0xfc, 0xd4, 0xcf, 0x58, 0xd1, 0x5b, 0xa8, 0x78, 0x51, 0x18, 0x52, 0x4f, 0x55, 0x3c, 0x8e, 0x22,
	0xdf, 0x5c, 0xfb, 0x70, 0x03, 0xef, 0xc9, 0x12, 0x31, 0x8c, 0x22, 0x7f, 0xc9, 0x5c, 0xf6, 0xee,
	0xd8, 0xd1, 0x8f, 0xb0, 0x1b, 0xa5, 0xc2, 0x67, 0x34, 0x71, 0xa7, 0x54, 0x68, 0x47, 0xd5, 0x52,
	0xec, 0x5f, 0x6c, 0x60, 0x1f, 0x68, 0x4c, 0x7b, 0x01, 0xc1, 0x76, 0x74, 0xcf, 0x82, 0x8e, 0xc1,
	0x12, 0x3e, 0xaf, 0x6e, 0x29, 0xae, 0xcf, 0x36, 0x35, 0xa8, 0x37, 0x5a, 0xa6, 0x27, 0x21, 0xf5,
	0x77, 0x39, 0x28, 0xe8, 0x5a, 0xaf, 0x1d, 0x82, 0x0e, 0x14, 0x7c, 0x32, 0xa1, 0x3e, 0xaf, 0xe6,
	0x55, 0xcb, 0x5e, 0xbc, 0xb7, 0x65, 0x4e, 0x4f, 0xc5, 0x77, 0x42, 0x91, 0xdc, 0x60, 0x03, 0x5e,
	0x33, 0x4b, 0xd6, 0xff, 0x9a, 0xa5, 0xda, 0x37, 0x50, 0xca, 0x9c, 0x83, 0x6c, 0xb0, 0x2e, 0xe9,
	0x8d, 0xc9, 0x5c, 0x7e, 0xa2, 0x3d, 0xd8, 0xbe, 0x22, 0x7e, 0x4a, 0x55, 0xf7, 0x8a, 0x58, 0xff,
	0xf8, 0x36, 0x7f, 0x9c, 0xab, 0xff, 0x6a, 0xc1, 0xde, 0xba, 0x41, 0x40, 0x18, 0x0a, 0x9c, 0x05,
	0xb1, 0xaf, 0x2b, 0x50, 0x3e, 0x3a, 0x7e, 0xe0, 0x24, 0x39, 0x23, 0x85, 0xee, 0xb5, 0xba, 0x8f,
	0xb0, 0x61, 0x42, 0x97, 0x6a, 0x9c, 0x38, 0xe3, 0x82, 0x86, 0xc2, 0x9d, 0x13, 0x3e, 0x37, 0xe3,
	0xf4, 0xfd, 0x43, 0xc9, 0x4f, 0x96, 0x34, 0x5d, 0xc2, 0xe7, 0xea, 0x90, 0xb2, 0x77, 0xc7, 0x56,
	0x73, 0xc1, 0xbe, 0x1f, 0x85, 0x3e, 0x81, 0xd2, 0x5c, 0x88, 0xd8, 0x9d, 0x53, 0x32, 0x35, 0x3b,
	0x52, 0xc4, 0x20, 0x4d, 0x5d, 0x65, 0x41, 0xcf, 0x61, 0x37, 0x60, 0x21, 0x0b, 0xd2, 0xc0, 0x4d,
	0x58, 0x38, 0x73, 0x39, 0xbb, 0xd5, 0x45, 0xdb, 0xc1, 0x15, 0xe3, 0xc0, 0x2c, 0x9c, 0x8d, 0xd8,
	0x2d, 0xad, 0x77, 0xe1, 0xc9, 0xe2, 0x8e, 0xa8, 0x02, 0x25, 0x3c, 0x38, 0xef, 0xb7, 0x5d, 0x3c,
	0x68, 0x9d, 0xf6, 0xed, 0x47, 0xa8, 0x0c, 0xd0, 0xeb, 0x34, 0x47, 0x63, 0xf7, 0x64, 0xd0, 0xef,
	0xdb, 0x39, 0x04, 0x50, 0xc0, 0xcd, 0x7e, 0x7b, 0x70, 0x66, 0xe7, 0x65, 0xf0, 0xb0, 0x39, 0x1a,
	0x8d, 0xbb, 0x78, 0x70, 0xfe, 0xa6, 0x6b, 0x5b, 0xad, 0x12, 0x14, 0xfd, 0x89, 0x99, 0x85, 0xfa,
	0x6f, 0x5b, 0xf0, 0xc1, 0xfa, 0x15, 0x42, 0x03, 0xb0, 0x84, 0x17, 0x9b, 0xd5, 0x7e, 0xfd, 0xe0,
	0x15, 0x74, 0xc6, 0x27, 0xc3, 0xcc, 0xbc, 0x7b, 0x31, 0xc2, 0xb0, 0x25, 0x2f, 0x6f, 0xba, 0xf0,
	0xdd, 0xc3, 0x19, 0xbb, 0xe3, 0xf1, 0x8a, 0x52, 0x71, 0xd5, 0x6e, 0xa1, 0x94, 0x39, 0x07, 0x7d,
	0x0e, 0x95, 0x80, 0x5c, 0xbb, 0xab, 0xe5, 0xe7, 0x2a, 0xff, 0x6d, 0x5c, 0x0e, 0xc8, 0xf5, 0x8a,
	0x95, 0xa3, 0xd6, 0x52, 0x6b, 0x5c, 0xc1, 0x02, 0x1a, 0xa5, 0xc2, 0xa4, 0xf5, 0xcc, 0xd1, 0x1a,
	0xee, 0x2c, 0x34, 0xdc, 0x69, 0x1b, 0x0d, 0x5f, 0x6a, 0xca, 0x58, 0x03, 0x6a, 0x7f, 0xe7, 0xe0,
	0x69, 0x36, 0x25, 0xf4, 0x0a, 0x6a, 0x32, 0xa9, 0x43, 0x57, 0xe6, 0x10, 0xd3, 0x70, 0x2a, 0x9b,
	0x9a, 0xd0, 0x9f, 0x53, 0xca, 0xc5, 0x22, 0x91, 0x0f, 0x55, 0xc4, 0x19, 0xb9, 0x1e, 0x6a, 0x3f,
	0x36, 0x6e, 0xf4, 0x25, 0x20, 0xe9, 0x3a, 0x52, 0xe0, 0x25, 0x28, 0xaf, 0x40, 0xb6, 0xf2, 0x9c,
	0x91, 0xeb, 0x65, 0xf4, 0x6b, 0xf8, 0x28, 0x1b, 0xe7, 0xc6, 0x34, 0xc9, 0xdc, 0x5a, 0xad, 0xf8,
	0x36, 0xae, 0x06, 0x2b, 0xc4, 0x90, 0x26, 0xab, 0xfb, 0xcb, 0xd1, 0xd4, 0x70, 0x91, 0x30, 0xaa,
	0xc5, 0x6b, 0x1b, 0x83, 0x0a, 0x57, 0x96, 0xfa, 0x9f, 0x79, 0xb0, 0xef, 0x8b, 0x1f, 0xea, 0x99,
	0x06, 0xea, 0x91, 0x38, 0x7e, 0x80, 0x6e, 0xae, 0x6b, 0xdd, 0xbb, 0xfb, 0xe5, 0x7b, 0x01, 0x48,
	0x6e, 0x15, 0xf5, 0x52, 0xc1, 0xae, 0xa8, 0x4b, 0x93, 0x24, 0x4a, 0x16, 0x65, 0xdb, 0xcd, 0x78,
	0x3a, 0xca, 0x81, 0xbe, 0x86, 0x27, 0x2c, 0x14, 0x34, 0xb9, 0x22, 0xfe, 0xfb, 0x7b, 0xb7, 0x0c,
	0x45, 0x6f, 0x00, 0x4d, 0x08, 0xa7, 0x2e, 0xfd, 0xc9, 0x3c, 0x34, 0xb2, 0xff, 0x46, 0x13, 0x37,
	0x10, 0xd8, 0x12, 0xd4, 0x31, 0x18, 0x39, 0x01, 0xe8, 0x2b, 0xd8, 0x93, 0x35, 0x5c, 0xf2, 0xc4,
	0x34, 0xf1, 0x68, 0x28, 0x4c, 0x31, 0x51, 0x40, 0xae, 0x17, 0xe1, 0x43, 0xed, 0xa9, 0xff, 0x91,
	0x87, 0x52, 0xe6, 0x15, 0x40, 0x2d, 0xd8, 0x0a, 0xa2, 0xe9, 0x42, 0xf3, 0x9c, 0xff, 0xf6, 0x76,
	0xc8, 0x6f, 0x89, 0xc2, 0x0a, 0xab, 0x8a, 0xe6, 0x33, 0xa9, 0x70, 0x1e, 0x4d, 0x04, 0xbb, 0x60,
	0x1e, 0x11, 0x0b, 0xe5, 0xdd, 0xd5, 0x9e, 0x93, 0x95, 0x43, 0x36, 0x3e, 0x4e, 0xd8, 0x15, 0x11,
	0xd4, 0x95, 0xaa, 0x6d, 0x69, 0x4d, 0x32, 0xa6, 0x1f, 0xe8, 0x8d, 0xdc, 0x20, 0x8f, 0x64, 0xb9,
	0xf4, 0x74, 0x14, 0x71, 0xd9, 0x23, 0x19, 0x22, 0x2e, 0xc5, 0x8b, 0xa7, 0x13, 0x79, 0x43, 0x97,
	0xf8, 0xc2, 0x95, 0x4f, 0x16, 0xaf, 0x6e, 0xef, 0x5b, 0x07, 0x45, 0x5c, 0x31, 0x8e, 0xa6, 0x2f,
	0xfa, 0xd2, 0x2c, 0xdf, 0x08, 0x1e, 0xb2, 0x6a, 0x41, 0xbf, 0x11, 0x3c, 0x64, 0x75, 0x07, 0x1e,
	0x9b, 0x7b, 0xa0, 0x12, 0x3c, 0x6e, 0x9f, 0x8e, 0x9a, 0xad, 0x5e, 0xc7, 0x7e, 0x24, 0x95, 0x6b,
	0x74, 0x7a, 0x36, 0xec, 0x75, 0xb4, 0x8a, 0x9d, 0x9d, 0x8f, 0xcf, 0x9b, 0x3d, 0x3b, 0xdf, 0xaa,
	0xbf, 0xdd, 0xd7, 0xd5, 0x61, 0x51, 0x83, 0xc4, 0xac, 0xb1, 0xe6, 0xff, 0xda, 0xa4, 0xa0, 0xba,
	0xf6, 0xf2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xc8, 0xfd, 0x3f, 0xcd, 0x09, 0x00, 0x00,
}
