filegroup(
    name = "istio-install",
    srcs = [
        "istio-egress.yaml",
        "istio-ingress.yaml",
        "istio-manager.yaml",
        "istio-mixer.yaml",
    ],
    visibility = ["//visibility:public"],
)
