package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "brkcol",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    deps = [
        "//cmd/brkcol/cmd:go_default_library",
        "//cmd/shared:go_default_library",
    ],
)
