#!/bin/bash
#
# Copyright 2016 Istio Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
set -ex
set -o errexit
set -o nounset
set -o pipefail

PROJECT="istio-testing"
DATE_PART=$(date +"%Y%m%d")
SHA_PART=$(git show -q HEAD --pretty=format:%h)
DOCKER_TAG="${DATE_PART}-${SHA_PART}"
BAZEL_TARGET="bazel-bin/src/envoy/mixer/envoy"
RELEASE_IMAGE_NAME="gcr.io/${PROJECT}/envoy:${DOCKER_TAG}"
DEBUG_IMAGE_NAME="gcr.io/${PROJECT}/envoy-debug:${DOCKER_TAG}"

gcloud docker --authorize-only

echo Publishing release docker image
bazel build --config=release //src/envoy/mixer:envoy
cp "${BAZEL_TARGET}" docker/
pushd docker
  docker build -f Dockerfile.release -t "${RELEASE_IMAGE_NAME}" .
  gcloud docker -- push "${RELEASE_IMAGE_NAME}"
  rm -f envoy
popd

echo Publishing debug docker image
bazel build -c dbg //src/envoy/mixer:envoy
cp "${BAZEL_TARGET}" docker/
pushd docker
  docker build -f Dockerfile.debug -t "${DEBUG_IMAGE_NAME}" .
  gcloud docker -- push "${DEBUG_IMAGE_NAME}"
  rm -f envoy
popd
