#!/bin/bash
#
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
set -ex

# Make sure to this script on x86_64 Ubuntu Xenial

# The bucket name to store proxy binary
BUCKET_NAME="istio-build/proxy"

# The proxy binary name.
BINARY_FORMAT='envoy-alpha-%H.tar.gz'
BINARY_NAME="$(git show -q HEAD --pretty=format:"${BINARY_FORMAT}")"

# Build the binary
bazel build --config=release //src/envoy/mixer:envoy_tar
SRC="bazel-bin/src/envoy/mixer/envoy_tar.tar.gz"
DST="gs://${BUCKET_NAME}/${BINARY_NAME}"

# Copy it to the bucket.
echo "Copying ${SRC} to ${DST}"
gsutil cp ${SRC} ${DST}


