#!/bin/bash
#
# Copyright 2016 Istio Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
set -ex

# This docker image can be used as:
#
# docker run IMAGE -a backend_address -p PORT -m MIXER_SERVER
#

PROJECT=istio-testing
IMAGE_PREFIX="gcr.io/${PROJECT}/envoy"

DATE_PART=$(date +"%Y%m%d")
SHA_PART=$(git show -q HEAD --pretty=format:%h)
DOCKER_TAG="${DATE_PART}${SHA_PART}"

IMAGE_NAME="${IMAGE_PREFIX}:${DOCKER_TAG}"

gcloud docker --authorize-only

bazel run --config=release //src/envoy/mixer:envoy_image "${IMAGE_NAME}"

gcloud docker -- push "${IMAGE_NAME}"

IMAGE_LATEST="${IMAGE_PREFIX}:latest"

docker tag -f "${IMAGE_NAME}" "${IMAGE_LATEST}"

gcloud docker -- push "${IMAGE_LATEST}"
