{
 "title": "Istio HTTP/GRPC Workload Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(istio_requests_total, destination_namespace)"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "label_values(istio_requests_total{destination_namespace=~\"$namespace\"}, destination_workload)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"$workload\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~\"$workload\",response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{destination_workload=~\"$workload\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\", response_code=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\", response_code=~\"5.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "Requests by Source and Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, response_code), 0.001)",
     "legendFormat": "{{ source_workload }} -> {{destination_workload}} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Success Rate by Source  (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\",response_code!~\"5.*\"}[1m])) by (source_workload, destination_workload) / sum(irate(istio_requests_total{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload)",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "Response Time by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p50)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p99)"
    }
   ]
  },
  {
   "title": "Response Size by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p50)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{destination_workload=~\"$workload\"}[1m])) by (source_workload, destination_workload, le))",
     "legendFormat": "{{ source_workload }} -> {{ destination_workload }} (p99)"
    }
   ]
  }
 ]
}