{
 "title": "Istio HTTP/GRPC Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(istio_request_count, destination_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_request_count{destination_service=~\"$service\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_request_count{destination_service=~\"$service\",response_code!~\"5.*\"}[1m])) / sum(rate(istio_request_count{destination_service=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_request_count{destination_service=~\"$service\", response_code=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_request_count{destination_service=~\"$service\", response_code=~\"5.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "Requests by Source, Version, and Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(round(sum(irate(istio_request_count{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, response_code), 0.001), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version}} -> {{destination_version}} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Success Rate by Source and Version (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_request_count{destination_service=~\"$service\",response_code!~\"5.*\"}[1m])) by (source_service, source_version, destination_version) / sum(irate(istio_request_count{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{source_service}}-{{source_version}} -> {{destination_version}}"
    }
   ]
  },
  {
   "title": "Response Time by Source and Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(irate(istio_request_duration_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(irate(istio_request_duration_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version,destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(irate(istio_request_duration_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version,destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(istio_request_duration_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p99)"
    }
   ]
  },
  {
   "title": "Response Size by Source and Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(irate(istio_response_size_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(irate(istio_response_size_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(irate(istio_response_size_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(istio_response_size_bucket{destination_service=~\"$service\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p99)"
    }
   ]
  }
 ]
}