load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "ca.go",
        "generate_cert.go",
    ],
    visibility = ["//visibility:public"],
)
