// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package model

import (
	"fmt"
	"sync"
	"time"

	discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	"github.com/google/go-cmp/cmp"
	"github.com/hashicorp/golang-lru/v2/simplelru"
	"golang.org/x/exp/slices"
	"google.golang.org/protobuf/testing/protocmp"

	"istio.io/istio/pilot/pkg/features"
	"istio.io/istio/pkg/util/sets"
	"istio.io/pkg/monitoring"
)

var enableStats = func() bool {
	return features.EnableXDSCacheMetrics
}

var (
	xdsCacheReads = monitoring.RegisterIf(monitoring.NewSum(
		"xds_cache_reads",
		"Total number of xds cache xdsCacheReads.",
		monitoring.WithLabels(typeTag)), enableStats)

	xdsCacheEvictions = monitoring.RegisterIf(monitoring.NewSum(
		"xds_cache_evictions",
		"Total number of xds cache evictions.",
		monitoring.WithLabels(typeTag)), enableStats)

	xdsCacheSize = monitoring.RegisterIf(monitoring.NewGauge(
		"xds_cache_size",
		"Current size of xds cache"), enableStats)

	dependentConfigSize = monitoring.RegisterIf(monitoring.NewGauge(
		"xds_cache_dependent_config_size",
		"Current size of dependent configs"), enableStats)

	xdsCacheHits             = xdsCacheReads.With(typeTag.Value("hit"))
	xdsCacheMisses           = xdsCacheReads.With(typeTag.Value("miss"))
	xdsCacheEvictionsOnClear = xdsCacheEvictions.With(typeTag.Value("clear"))
	xdsCacheEvictionsOnSize  = xdsCacheEvictions.With(typeTag.Value("size"))
)

func hit() {
	xdsCacheHits.Increment()
}

func miss() {
	xdsCacheMisses.Increment()
}

func size(cs int) {
	xdsCacheSize.Record(float64(cs))
}

type KeyHash uint64

// XdsCacheEntry interface defines functions that should be implemented by
// resources that can be cached.
type XdsCacheEntry interface {
	// Key is the key to be used in cache.
	Key() KeyHash
	// DependentConfigs is config items that this cache key is dependent on.
	// Whenever these configs change, we should invalidate this cache entry.
	DependentConfigs() []ConfigHash
	// Cacheable indicates whether this entry is valid for cache. For example
	// for EDS to be cacheable, the Endpoint should have corresponding service.
	Cacheable() bool
}

type CacheToken uint64

// XdsCache interface defines a store for caching XDS responses.
// All operations are thread safe.
type XdsCache interface {
	// Run starts a background thread periodically flush evicted indexes
	Run(stop <-chan struct{})
	// Add adds the given XdsCacheEntry with the value for the given pushContext to the cache.
	// If the cache has been updated to a newer push context, the write will be dropped silently.
	// This ensures stale data does not overwrite fresh data when dealing with concurrent
	// writers.
	Add(entry XdsCacheEntry, pushRequest *PushRequest, value *discovery.Resource, opts ...CacheOption)
	// Get retrieves the cached value if it exists.
	Get(entry XdsCacheEntry) *discovery.Resource
	// GetWithRequest retrieves the cached value if it was generated by a newer push request.
	GetWithRequest(entry XdsCacheEntry, pushReq *PushRequest) *discovery.Resource
	// Clear removes the cache entries that are dependent on the configs passed.
	Clear(sets.Set[ConfigKey])
	// ClearAll clears the entire cache.
	ClearAll()
	// Keys returns all currently configured keys. This is for testing/debug only
	Keys() []KeyHash
	// Snapshot returns a snapshot of all keys and values. This is for testing/debug only
	Snapshot() map[KeyHash]*discovery.Resource
}

// NewXdsCache returns an instance of a cache.
func NewXdsCache() XdsCache {
	cache := &lruCache{
		enableAssertions: features.EnableUnsafeAssertions,
		configIndex:      map[ConfigHash]sets.Set[KeyHash]{},
		evictQueue:       make([]evictKeyConfigs, 0, 1000),
	}
	cache.store = newLru(cache.onEvict)
	return cache
}

type evictKeyConfigs struct {
	key              KeyHash
	dependentConfigs []ConfigHash
}

type lruCache struct {
	enableAssertions bool
	store            simplelru.LRUCache[KeyHash, cacheValue]
	// token stores the latest token of the store, used to prevent stale data overwrite.
	// It is refreshed when Clear or ClearAll are called
	token       CacheToken
	mu          sync.RWMutex
	configIndex map[ConfigHash]sets.Set[KeyHash]

	evictQueue []evictKeyConfigs

	// mark whether a key is evicted on Clear call, passively.
	evictedOnClear bool
}

var _ XdsCache = &lruCache{}

func newLru(evictCallback simplelru.EvictCallback[KeyHash, cacheValue]) simplelru.LRUCache[KeyHash, cacheValue] {
	sz := features.XDSCacheMaxSize
	if sz <= 0 {
		sz = 20000
	}
	l, err := simplelru.NewLRU(sz, evictCallback)
	if err != nil {
		panic(fmt.Errorf("invalid lru configuration: %v", err))
	}
	return l
}

func (l *lruCache) Run(stop <-chan struct{}) {
	interval := features.XDSCacheIndexClearInterval
	go func() {
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				l.mu.Lock()
				for _, keyConfigs := range l.evictQueue {
					l.clearConfigIndex(keyConfigs.key, keyConfigs.dependentConfigs)
				}
				l.evictQueue = l.evictQueue[:0:1000]
				l.recordDependentConfigSize()
				l.mu.Unlock()
			case <-stop:
				return
			}
		}
	}()
}

func (l *lruCache) recordDependentConfigSize() {
	if !enableStats() {
		return
	}
	dsize := 0
	for _, dependents := range l.configIndex {
		dsize += len(dependents)
	}
	dependentConfigSize.Record(float64(dsize))
}

// This is the callback passed to LRU, it will be called whenever a key is removed.
func (l *lruCache) onEvict(k KeyHash, v cacheValue) {
	if l.evictedOnClear {
		xdsCacheEvictionsOnClear.Increment()
	} else {
		xdsCacheEvictionsOnSize.Increment()
	}

	// async clearing indexes
	l.evictQueue = append(l.evictQueue, evictKeyConfigs{k, v.dependentConfigs})
}

func (l *lruCache) updateConfigIndex(k KeyHash, dependentConfigs []ConfigHash) {
	for _, cfg := range dependentConfigs {
		sets.InsertOrNew(l.configIndex, cfg, k)
	}
}

func (l *lruCache) clearConfigIndex(k KeyHash, dependentConfigs []ConfigHash) {
	c, exists := l.store.Get(k)
	if exists {
		newDependents := c.dependentConfigs
		// we only need to clear configs {old difference new}
		dependents := sets.New[ConfigHash](dependentConfigs...).Difference(sets.New[ConfigHash](newDependents...))
		for cfg := range dependents {
			sets.DeleteCleanupLast(l.configIndex, cfg, k)
		}
		return
	}
	for _, cfg := range dependentConfigs {
		sets.DeleteCleanupLast(l.configIndex, cfg, k)
	}
}

// assertUnchanged checks that a cache entry is not changed. This helps catch bad cache invalidation
// We should never have a case where we overwrite an existing item with a new change. Instead, when
// config sources change, Clear/ClearAll should be called. At this point, we may get multiple writes
// because multiple writers may get cache misses concurrently, but they ought to generate identical
// configuration. This also checks that our XDS config generation is deterministic, which is a very
// important property.
func (l *lruCache) assertUnchanged(key KeyHash, existing *discovery.Resource, replacement *discovery.Resource) {
	if l.enableAssertions {
		if existing == nil {
			// This is a new addition, not an update
			return
		}
		// Record time so that we can correlate when the error actually happened, since the async reporting
		// may be delayed
		t0 := time.Now()
		// This operation is really slow, which makes tests fail for unrelated reasons, so we process it async.
		go func() {
			if !cmp.Equal(existing, replacement, protocmp.Transform()) {
				warning := fmt.Errorf("assertion failed at %v, cache entry changed but not cleared for key %v: %v\n%v\n%v",
					t0, key, cmp.Diff(existing, replacement, protocmp.Transform()), existing, replacement)
				panic(warning)
			}
		}()
	}
}

type CacheOption struct {
	// when IgnoreOldCache is true, it will not assert cache value unchanged
	// note: currently it is used for EDS when PA updated
	IgnoreOldCache bool
}

func (l *lruCache) Add(entry XdsCacheEntry, pushReq *PushRequest, value *discovery.Resource, opts ...CacheOption) {
	if !entry.Cacheable() || pushReq == nil || pushReq.Start.Equal(time.Time{}) {
		return
	}
	// It will not overflow until year 2262
	token := CacheToken(pushReq.Start.UnixNano())
	k := entry.Key()
	l.mu.Lock()
	defer l.mu.Unlock()
	if token < l.token {
		// entry may be stale, we need to drop it. This can happen when the cache is invalidated
		// after we call Get.
		return
	}
	cur, f := l.store.Get(k)
	if f {
		// This is the stale or same resource
		if token <= cur.token {
			return
		}
		if l.enableAssertions {
			for _, opt := range opts {
				if opt.IgnoreOldCache {
					continue
				}
			}
			l.assertUnchanged(k, cur.value, value)
		}
	}

	dependentConfigs := entry.DependentConfigs()
	toWrite := cacheValue{value: value, token: token, dependentConfigs: dependentConfigs}
	l.store.Add(k, toWrite)
	l.token = token
	l.updateConfigIndex(k, dependentConfigs)

	// we have to make sure we evict old entries with the same key
	// to prevent leaking in the index maps
	if f {
		l.evictQueue = append(l.evictQueue, evictKeyConfigs{k, cur.dependentConfigs})
	}
	size(l.store.Len())
}

type cacheValue struct {
	value            *discovery.Resource
	token            CacheToken
	dependentConfigs []ConfigHash
}

func (l *lruCache) Get(entry XdsCacheEntry) *discovery.Resource {
	return l.get(entry, 0)
}

// GetWithRequest return the cached value generated by newer push request than the given one.
func (l *lruCache) GetWithRequest(entry XdsCacheEntry, pushReq *PushRequest) *discovery.Resource {
	return l.get(entry, CacheToken(pushReq.Start.UnixNano()))
}

// get return the cached value if it exists.
func (l *lruCache) get(entry XdsCacheEntry, token CacheToken) *discovery.Resource {
	if !entry.Cacheable() {
		return nil
	}
	k := entry.Key()
	l.mu.Lock()
	defer l.mu.Unlock()
	cv, ok := l.store.Get(k)
	if !ok || cv.value == nil {
		miss()
		return nil
	}
	if cv.token >= token {
		hit()
		return cv.value
	}
	miss()
	return nil
}

func (l *lruCache) Clear(configs sets.Set[ConfigKey]) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.token = CacheToken(time.Now().UnixNano())
	l.evictedOnClear = true
	defer func() {
		l.evictedOnClear = false
	}()
	for ckey := range configs {
		referenced := l.configIndex[ckey.HashCode()]
		delete(l.configIndex, ckey.HashCode())
		for key := range referenced {
			l.store.Remove(key)
		}
	}
	size(l.store.Len())
}

func (l *lruCache) ClearAll() {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.token = CacheToken(time.Now().UnixNano())
	// Purge with an evict function would turn up to be pretty slow since
	// it runs the function for every key in the store, might be better to just
	// create a new store.
	l.store = newLru(l.onEvict)
	l.configIndex = map[ConfigHash]sets.Set[KeyHash]{}
	l.evictQueue = l.evictQueue[:0:1000]
	size(l.store.Len())
}

func (l *lruCache) Keys() []KeyHash {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return slices.Clone(l.store.Keys())
}

func (l *lruCache) Snapshot() map[KeyHash]*discovery.Resource {
	l.mu.RLock()
	defer l.mu.RUnlock()
	iKeys := l.store.Keys()
	res := make(map[KeyHash]*discovery.Resource, len(iKeys))
	for _, ik := range iKeys {
		v, ok := l.store.Get(ik)
		if !ok {
			continue
		}

		res[ik] = v.value
	}
	return res
}

func (l *lruCache) indexLength() int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return len(l.configIndex)
}

func (l *lruCache) configIndexSnapshot() map[ConfigHash]sets.Set[KeyHash] {
	l.mu.RLock()
	defer l.mu.RUnlock()
	res := make(map[ConfigHash]sets.Set[KeyHash], len(l.configIndex))
	for k, v := range l.configIndex {
		res[k] = v
	}
	return res
}

// DisabledCache is a cache that is always empty
type DisabledCache struct{}

var _ XdsCache = &DisabledCache{}

func (d DisabledCache) Run(stop <-chan struct{}) {
}

func (d DisabledCache) Add(key XdsCacheEntry, pushReq *PushRequest, value *discovery.Resource, opts ...CacheOption) {
}

func (d DisabledCache) Get(XdsCacheEntry) *discovery.Resource {
	return nil
}

func (d DisabledCache) GetWithRequest(entry XdsCacheEntry, pushReq *PushRequest) *discovery.Resource {
	return nil
}

func (d DisabledCache) Clear(configsUpdated sets.Set[ConfigKey]) {}

func (d DisabledCache) ClearAll() {}

func (d DisabledCache) Keys() []KeyHash { return nil }

func (d DisabledCache) Snapshot() map[KeyHash]*discovery.Resource { return nil }
