package(default_visibility = ["//visibility:public"])

filegroup(
    name = "descriptor_set",
    testonly = True,
    srcs = [
        "template_proto.descriptor_set",
    ],
)

filegroup(
    name = "baseline",
    testonly = True,
    srcs = [
        "template.baseline",
    ],
)
