FROM centos:8

# hadolint ignore=DL3005,DL3008
RUN yum upgrade -y && \
    yum install -y \
    iptables \
    iproute \
    sudo \
    && update-ca-trust \
    yum clean all && \
    rm -rf /var/cache/yum

# Add a user that will run the application. This allows running as this user and capture iptables
RUN useradd -m --uid 1338 application && \
    echo "application ALL=NOPASSWD: ALL" >> /etc/sudoers
