# hadolint ignore=DL3006
FROM istionightly/base_debug

# Install the certs.
COPY certs/                           /var/lib/istio/
COPY certs/default/*                  /etc/certs/

# Install the sidecar components
COPY envoy                            /usr/local/bin/envoy
COPY pilot-agent                      /usr/local/bin/pilot-agent
COPY node_agent                       /usr/local/bin/node_agent
COPY istio-start.sh                   /usr/local/bin/istio-start.sh
COPY istio-node-agent-start.sh        /usr/local/bin/istio-node-agent-start.sh
COPY istio-iptables.sh                /usr/local/bin/istio-iptables
COPY istio-clean-iptables.sh          /usr/local/bin/istio-clean-iptables
COPY postinst.sh                      /usr/local/bin/postinst.sh
COPY envoy_bootstrap_v2.json          /var/lib/istio/envoy/envoy_bootstrap_tmpl.json
COPY envoy_bootstrap_drain.json       /var/lib/istio/envoy/envoy_bootstrap_drain.json

# Install the Echo application
COPY echo-start.sh /usr/local/bin/echo-start.sh
COPY client /usr/local/bin/client
COPY server /usr/local/bin/server
ENTRYPOINT ["/usr/local/bin/echo-start.sh"]
