FROM centos:8

# hadolint ignore=DL3005,DL3008
RUN yum upgrade -y && \
    yum install -y \
    iptables \
    iproute \
    sudo \
    && update-ca-trust \
    yum clean all && \
    rm -rf /var/cache/yum

# Add a user that will run the application. This allows running as this user and capture iptables
RUN useradd -m --uid 1338 application && \
    echo "application ALL=NOPASSWD: ALL" >> /etc/sudoers

# Install the certs.
COPY certs/                           /var/lib/istio/
COPY certs/default/*                  /var/run/secrets/istio/

# Install the sidecar components
COPY istio-sidecar.rpm  /tmp/istio-sidecar.rpm
RUN rpm -vi /tmp/istio-sidecar.rpm && rm /tmp/istio-sidecar.rpm

# Sudoers used to allow tcpdump and other debug utilities.
RUN echo "istio-proxy ALL=NOPASSWD: ALL" >> /etc/sudoers

# Install the Echo application
COPY echo-start.sh /usr/local/bin/echo-start.sh
COPY client /usr/local/bin/client
COPY server /usr/local/bin/server
RUN chmod +x /usr/local/bin/client /usr/local/bin/server

ENTRYPOINT ["/usr/local/bin/echo-start.sh"]
