{
 "title": "Istio Citadel Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage across Citadel instances.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"citadel\", pod_name=~\"istio-citadel-.*\"}[1m]))",
     "legendFormat": "Citadel CPU usage rate"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"citadel\"}[1m])",
     "legendFormat": "Citadel CPU usage irate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Citadel process memory statistics.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"citadel\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"citadel\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Memory Total"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Memory Allocated"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"citadel\"}",
     "legendFormat": "Heap Inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"citadel\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CSR Requests",
   "type": "graph",
   "description": "Total number of CSR requests made to Citadel.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_csr_count{job=\"citadel\"}",
     "legendFormat": "CSR Request Count"
    }
   ]
  },
  {
   "title": "Certificates Issued",
   "type": "graph",
   "description": "The number of certificates issuances that have succeeded.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_success_cert_issuance_count{job=\"citadel\"}",
     "legendFormat": "Certificates Issued"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CSR Creation Errors",
   "type": "graph",
   "description": "The number of errors occurred when creating the CSR.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_csr_err_count{job=\"citadel\"}",
     "legendFormat": "CSR Creation Error Count"
    }
   ]
  },
  {
   "title": "CSR Parse Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_csr_parsing_err_count{job=\"citadel\"}",
     "legendFormat": "CSR Parse Error Count"
    }
   ]
  },
  {
   "title": "Authentication Failures",
   "type": "graph",
   "description": "The number of authentication failures.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citadel_server_authentication_failure_count{job=\"citadel\"}\t",
     "legendFormat": "Authentication Failure Count"
    }
   ]
  },
  { "title": "Secret Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Service Account Secrets Created (due to SA creation)",
   "type": "graph",
   "description": "The number of certificates created due to service account creation.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_svc_acc_created_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Created"
    }
   ]
  },
  {
   "title": "Service Account Secrets Deleted (due to SA deletion)",
   "type": "graph",
   "description": "The number of certificates deleted due to service account deletion.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_svc_acc_deleted_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Deleted"
    }
   ]
  },
  {
   "title": "Service Account Secrets Recreated (due to errant deletion)",
   "type": "graph",
   "description": "The number of certificates recreated due to secret deletion (service account still exists).",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Certs Created" }
   ],
   "targets": [
    {
     "expr": "citadel_secret_controller_secret_deleted_cert_count{job=\"citadel\"}",
     "legendFormat": "SA Secrets Recreated"
    }
   ]
  }
 ]
}
{
 "title": "Istio Galley Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Galley Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"galley\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"galley\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"galley\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"galley\"}",
     "legendFormat": "heap sys"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"galley\"}",
     "legendFormat": "heap alloc"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"galley\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"galley\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"galley\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"})",
     "legendFormat": "Total (kis)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"galley\"}[1m])",
     "legendFormat": "galley (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"galley\"}",
     "legendFormat": "Open FDs (galley)"
    },
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"galley\", pod_name=~\"istio-galley-.*\"}",
     "legendFormat": "{{ container_name }} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"galley\"}",
     "legendFormat": "goroutines_total"
    },
    {
     "expr": "galley_mcp_source_clients_total",
     "legendFormat": "clients_total"
    },
    {
     "expr": "go_goroutines{job=\"galley\"}/galley_mcp_source_clients_total",
     "legendFormat": "avg_goroutines_per_client"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Event Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_on_change_total[1m])) * 60",
     "legendFormat": "Strategy Change Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_events_processed_total[1m])) * 60",
     "legendFormat": "Processed Events"
    },
    {
     "expr": "sum(rate(galley_runtime_processor_snapshots_published_total[1m])) * 60",
     "legendFormat": "Snapshot Published"
    }
   ]
  },
  {
   "title": "Timer Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_max_time_reached_total[1m])) * 60",
     "legendFormat": "Max Time Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_quiesce_reached_total[1m])) * 60",
     "legendFormat": "Quiesce Reached"
    },
    {
     "expr": "sum(rate(galley_runtime_strategy_timer_resets_total[1m])) * 60",
     "legendFormat": "Timer Resets"
    }
   ]
  },
  {
   "title": "Events Per Snapshot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (galley_runtime_processor_snapshot_events_total_bucket))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "State Type Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (typeURL) (galley_runtime_state_type_instances_total)",
     "legendFormat": "{{ typeURL }}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Validation Webhook Certificate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "galley_validation_cert_key_updates{job=\"galley\"}",
     "legendFormat": "Key Updates"
    },
    {
     "expr": "galley_validation_cert_key_update_errors{job=\"galley\"}",
     "legendFormat": "Key Update Errors: {{ error }}"
    }
   ]
  },
  {
   "title": "Resource Validation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_passed{job=\"galley\"}) by (group, version, resource)",
     "legendFormat": "Passed: {{ group }}/{{ version }}/{{resource}}"
    },
    {
     "expr": "sum(galley_validation_failed{job=\"galley\"}) by (group, version, resource, reason)",
     "legendFormat": "Failed: {{ group }}/{{ version }}/{{resource}} ({{ reason}})"
    }
   ]
  },
  {
   "title": "Validation HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_http_error{job=\"galley\"}) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Kubernetes Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Source Event Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Events/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_source_kube_event_success_total[1m]) * 60",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(galley_source_kube_event_error_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Kubernetes Object Conversion Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Failures/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_source_kube_dynamic_converter_failure_total[1m]) * 60",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Mesh Configuration Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_mcp_source_clients_total)",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Request ACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "ACKs/min" }
   ],
   "targets": [
    {
     "expr": "sum by(collection)(irate(galley_mcp_source_request_acks_total[1m]) * 60)"
    }
   ]
  },
  {
   "title": "Request NACKs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "NACKs/min" }
   ],
   "targets": [
    {
     "expr": "rate(galley_mcp_source_request_nacks_total[1m]) * 60"
    }
   ]
  }
 ]
}
{
 "title": "Istio Mesh Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n  <div style=\"position: absolute; bottom: 0\">\n    <a href=\"https://istio.io\" target=\"_blank\" style=\"font-size: 30px; text-decoration: none; color: inherit\"><img src=\"https://istio.io/img/istio-logo.svg\" style=\"height: 50px\"> Istio</a>\n  </div>\n  <div style=\"position: absolute; bottom: 0; right: 0; font-size: 15px\">\n    Istio is an <a href=\"https://github.com/istio/istio\" target=\"_blank\">open platform</a> that provides a uniform way to connect,\n    <a href=\"https://istio.io/docs/concepts/traffic-management/overview.html\" target=\"_blank\">manage</a>, and \n    <a href=\"https://istio.io/docs/concepts/network-and-auth/auth.html\" target=\"_blank\">secure</a> microservices.\n    <br>\n    Need help? Join the <a href=\"https://istio.io/community/\" target=\"_blank\">Istio community</a>.\n  </div>\n</div>"
  },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"destination\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"5.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "HTTP/GRPC Workloads",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_requests_total{reporter=\"destination\", response_code=\"200\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\"}[1m])) by (destination_workload, destination_workload_namespace) / sum(rate(istio_requests_total{reporter=\"destination\"}[1m])) by (destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "TCP Workloads",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_tcp_received_bytes_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    },
    {
     "expr": "label_join(sum(rate(istio_tcp_sent_bytes_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    }
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Performance Dashboard Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Performance Dashboard README",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "content": "The charts on this dashboard are intended to show Istio main components cost in terms resources utilization under steady load.\n\n- **vCPU/1k rps:** shows vCPU utilization by the main Istio components normalized by 1000 requests/second. When idle or low traffic, this chart will be blank. The curve for istio-proxy refers to the services sidecars only.\n- **vCPU:** vCPU utilization by Istio components, not normalized.\n- **Memory:** memory footprint for the components. Telemetry and policy are normalized by 1k rps, and no data is shown  when there is no traffic. For ingress and istio-proxy, the data is per instance.\n- **Bytes transferred/ sec:** shows the number of bytes flowing through each Istio component.\n\n\n"
    }
   ]
  },
  { "title": "vCPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "vCPU / 1k rps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-telemetry-.*\",container_name=~\"mixer|istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-telemetry"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\",container_name=\"istio-proxy\"}[1m])) / (round(sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m])), 0.001)/1000))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",namespace!=\"istio-system\",container_name=\"istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-proxy"
    },
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-policy-.*\",container_name=~\"mixer|istio-proxy\"}[1m]))/ (round(sum(irate(istio_requests_total[1m])), 0.001)/1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-policy"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-telemetry-.*\",container_name=~\"mixer|istio-proxy\"}[1m]))",
     "legendFormat": "istio-telemetry"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\",container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",namespace!=\"istio-system\",container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-proxy"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",pod_name=~\"istio-policy-.*\",container_name=~\"mixer|istio-proxy\"}[1m]))",
     "legendFormat": "istio-policy"
    }
   ]
  },
  { "title": "Memory and Data Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",pod_name=~\"istio-telemetry-.*\"}) / (sum(irate(istio_requests_total[1m])) / 1000)) / (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-telemetry / 1k rps"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\"}) / count(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",pod_name=~\"istio-ingressgateway-.*\",container_name!=\"POD\"})",
     "legendFormat": "per istio-ingressgateway"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",namespace!=\"istio-system\",container_name=\"istio-proxy\"}) / count(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",namespace!=\"istio-system\",container_name=\"istio-proxy\"})",
     "legendFormat": "per istio proxy"
    },
    {
     "expr": "(sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",pod_name=~\"istio-policy-.*\"}) / (sum(irate(istio_requests_total[1m])) / 1000))/ (sum(irate(istio_requests_total{source_workload=\"istio-ingressgateway\"}[1m])) >bool 10)",
     "legendFormat": "istio-policy / 1k rps"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{destination_workload=\"istio-telemetry\"}[1m])) + sum(irate(istio_request_bytes_sum{destination_workload=\"istio-telemetry\"}[1m]))",
     "legendFormat": "istio-telemetry"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload=\"istio-ingressgateway\", reporter=\"source\"}[1m]))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_response_bytes_sum{destination_workload_namespace!=\"istio-system\", reporter=\"destination\"}[1m])) + sum(irate(istio_request_bytes_sum{source_workload_namespace!=\"istio-system\", reporter=\"source\"}[1m])) + sum(irate(istio_request_bytes_sum{destination_workload_namespace!=\"istio-system\", reporter=\"destination\"}[1m]))",
     "legendFormat": "istio-proxy"
    },
    {
     "expr": "sum(irate(istio_response_bytes_sum{destination_workload=\"istio-policy\"}[1m])) + sum(irate(istio_request_bytes_sum{destination_workload=\"istio-policy\"}[1m]))",
     "legendFormat": "istio_policy"
    }
   ]
  },
  { "title": "Istio Component Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Istio Components by Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  },
  { "title": "Proxy Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=\"istio-proxy\"})",
     "legendFormat": "{{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=\"istio-proxy\"})",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  { "title": "Pilot Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"pilot\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "{{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"pilot\"}[1m])",
     "legendFormat": "pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"pilot\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  },
  { "title": "Mixer Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=~\"istio-telemetry|istio-policy\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"istio-telemetry|istio-policy\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=~\"istio-telemetry|istio-policy\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"istio-policy|istio-telemetry\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*\"}",
     "legendFormat": "{{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"istio-policy|istio-telemetry\"}[1m])",
     "legendFormat": "mixer (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"istio-telemetry\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  }
 ]
}
{
 "title": "Istio Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(destination_service)"
   },
   {
    "name": "srcns",
    "label": "Client Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\"}) by (source_workload_namespace))"
   },
   {
    "name": "srcwl",
    "label": "Client Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service\", source_workload_namespace=~\"$srcns\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\", source_workload_namespace=~\"$srcns\"}) by (source_workload))"
   },
   {
    "name": "dstns",
    "label": "Service Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service\"}) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\"}) by (destination_workload_namespace))"
   },
   {
    "name": "dstwl",
    "label": "Service Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service\", destination_workload_namespace=~\"$dstns\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service\", destination_workload_namespace=~\"$dstns\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>SERVICE: $service</span>\n</div>"
  },
  {
   "title": "Client Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Client Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "TCP Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", destination_service=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Server Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Server Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "TCP Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"source\", destination_service=~\"$service\"}[1m])) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>CLIENT WORKLOADS</span>\n</div>"
  },
  {
   "title": "Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service\",reporter=\"source\",source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", reporter=\"source\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"source\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"source\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>SERVICE WORKLOADS</span>\n</div>"
  },
  {
   "title": "Incoming Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service\",reporter=\"destination\",destination_workload=~\"$dstwl\",destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", reporter=\"destination\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\",response_code!~\"5.*\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[5m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"source\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"source\", destination_service=~\"$service\", destination_workload=~\"$dstwl\", destination_workload_namespace=~\"$dstns\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Workload Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(istio_requests_total) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total) by (destination_workload_namespace))"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "query_result((sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_requests_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)) or (sum(istio_tcp_sent_bytes_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)))"
   },
   {
    "name": "srcns",
    "label": "Inbound Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\"}) by (source_workload_namespace))"
   },
   {
    "name": "srcwl",
    "label": "Inbound Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload_namespace=~\"$srcns\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_workload=\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload_namespace=~\"$srcns\"}) by (source_workload))"
   },
   {
    "name": "dstsvc",
    "label": "Destination Service",
    "query": "query_result( sum(istio_requests_total{reporter=\"source\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"}) by (destination_service) or sum(istio_tcp_sent_bytes_total{reporter=\"source\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\"}) by (destination_service))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>WORKLOAD: $workload.$namespace</span>\n</div>"
  },
  {
   "title": "Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "TCP Server Traffic",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\"}[1m])) + sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\"}[1m]))"
    }
   ]
  },
  {
   "title": "TCP Client Traffic",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\"}[1m])) + sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\"}[1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>INBOUND WORKLOADS</span>\n</div>"
  },
  {
   "title": "Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", reporter=\"destination\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", reporter=\"destination\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Incoming Success Rate (non-5xx responses) By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Incoming Request Duration by Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload=~\"$workload\", destination_workload_namespace=~\"$namespace\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} P99"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"destination\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"destination\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$workload\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>OUTBOUND SERVICES</span>\n</div>"
  },
  {
   "title": "Outgoing Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", reporter=\"source\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Outgoing Success Rate (non-5xx responses) By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",response_code!~\"5.*\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[5m])) by (destination_service)",
     "legendFormat": "{{destination_service }}"
    }
   ]
  },
  {
   "title": "Outgoing Request Duration by Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P99 (🔐mTLS)"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Outgoing Request Size By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Response Size By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }}  P99 (🔐mTLS)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload=~\"$workload\", source_workload_namespace=~\"$namespace\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P99"
    }
   ]
  },
  {
   "title": "Bytes Sent on Outgoing TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"source\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "Bytes Received from Outgoing TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
     "legendFormat": "{{ destination_service }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\", destination_service=~\"$dstsvc\"}[1m])) by (destination_service), 0.001)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  }
 ]
}
{
 "title": "Istio Mixer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "adapter", "label": "Adapter", "query": "label_values(adapter)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Deployed Versions</h2></center>"
  },
  {
   "title": "Mixer Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"mixer\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "content": "<center><h2>Resource Usage</h2></center>"
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Virtual Memory ({{ job }})"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Resident Memory ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Alloc ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Heap in-use ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Stack in-use ({{ job }})"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (service)",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (container_name, pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=~\"istio-telemetry|istio-policy\"}[1m])) by (job)",
     "legendFormat": "{{ job }} (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Number of Goroutines ({{ job }})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "content": "<center><h2>Mixer Overview</h2></center>"
  },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs[1m]))",
     "legendFormat": "mixer (Total)"
    },
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs[1m])) by (grpc_server_method)",
     "legendFormat": "mixer ({{ grpc_server_method }})"
    }
   ]
  },
  {
   "title": "Response Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.99"
    }
   ]
  },
  {
   "title": "Server Error Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=~\"Unknown|Unimplemented|Internal|DataLoss\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Non-successes (4xxs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{grpc_code!=\"OK\",grpc_service=~\".*Mixer\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "content": "<center><h2>Adapters and Config</h2></center>"
  },
  {
   "title": "Adapter Dispatch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mixer_runtime_dispatches_total{adapter=~\"$adapter\"}[1m])) by (adapter)",
     "legendFormat": "{{ adapter }}"
    }
   ]
  },
  {
   "title": "Adapter Dispatch Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p90 "
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p99"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_count) by (configID)))",
     "legendFormat": "Rules"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_error_count) by (configID)))",
     "legendFormat": "Config Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_match_error_count) by (configID)))",
     "legendFormat": "Match Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_unsatisfied_action_handler_count) by (configID)))",
     "legendFormat": "Unsatisfied Actions"
    }
   ]
  },
  {
   "title": "Instances in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_instance_config_count) by (configID)))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Handlers in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_handler_config_count) by (configID)))",
     "legendFormat": "Handlers"
    }
   ]
  },
  {
   "title": "Attributes in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_attribute_count) by (configID)))",
     "legendFormat": "Attributes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "content": "<center><h2>Individual Adapters</h2></center>"
  },
  { "title": "$adapter Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "adapter" },
  {
   "title": "Dispatch Count By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mixer_runtime_dispatches_total{adapter=~\"$adapter\"}[1m]),\"handler\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "{{ handler }} (error: {{  error }})"
    }
   ]
  },
  {
   "title": "Dispatch Duration By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum(rate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p50 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p90 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p99 - {{ handler_short }} (error: {{ error }})"
    }
   ]
  }
 ]
}
{
 "title": "Istio Pilot Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Deployed Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pilot Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"pilot\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"discovery\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "Discovery (container)"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\", container_name=~\"istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "Sidecar (container)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=\"discovery\", pod_name=~\"istio-pilot-.*\"}[1m]))",
     "legendFormat": "Discovery (container)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"pilot\"}[1m])",
     "legendFormat": "Discovery (process)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",container_name=\"istio-proxy\", pod_name=~\"istio-pilot-.*\"}[1m]))",
     "legendFormat": "Sidecar (container)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=\"discovery\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "Discovery"
    },
    {
     "expr": "container_fs_usage_bytes{job=\"kubernetes-cadvisor\", container_name=\"istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "Sidecar"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"pilot\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  },
  { "title": "Pilot Push Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Pilot Pushes",
   "type": "graph",
   "description": "Shows the rate of pilot pushes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"cds\"}[1m]))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"eds\"}[1m]))",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"lds\"}[1m]))",
     "legendFormat": "Listeners"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"rds\"}[1m]))",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Pilot Errors",
   "type": "graph",
   "description": "Captures a variety of pilot errors",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pilot_xds_cds_reject{job=\"pilot\"}) or (absent(pilot_xds_cds_reject{job=\"pilot\"}) - 1)",
     "legendFormat": "Rejected CDS Configs"
    },
    {
     "expr": "sum(pilot_xds_eds_reject{job=\"pilot\"}) or (absent(pilot_xds_eds_reject{job=\"pilot\"}) - 1)",
     "legendFormat": "Rejected EDS Configs"
    },
    {
     "expr": "sum(pilot_xds_rds_reject{job=\"pilot\"}) or (absent(pilot_xds_rds_reject{job=\"pilot\"}) - 1)",
     "legendFormat": "Rejected RDS Configs"
    },
    {
     "expr": "sum(pilot_xds_lds_reject{job=\"pilot\"}) or (absent(pilot_xds_lds_reject{job=\"pilot\"}) - 1)",
     "legendFormat": "Rejected LDS Configs"
    },
    {
     "expr": "sum(rate(pilot_xds_write_timeout{job=\"pilot\"}[1m]))",
     "legendFormat": "Write Timeouts"
    },
    {
     "expr": "sum(rate(pilot_total_xds_internal_errors{job=\"pilot\"}[1m]))",
     "legendFormat": "Internal Errors"
    },
    {
     "expr": "sum(rate(pilot_total_xds_rejects{job=\"pilot\"}[1m]))",
     "legendFormat": "Config Rejection Rate"
    },
    {
     "expr": "sum(rate(pilot_xds_push_context_errors{job=\"pilot\"}[1m]))",
     "legendFormat": "Push Context Errors"
    },
    {
     "expr": "sum(rate(pilot_xds_pushes{type!~\"lds|cds|rds|eds\"}[1m])) by (type)",
     "legendFormat": "Push Errors ({{ type }})"
    },
    {
     "expr": "sum(rate(pilot_xds_push_errors{job=\"pilot\"}[1m])) by (type)",
     "legendFormat": "Push Errors ({{ type }})"
    },
    {
     "expr": "sum(rate(pilot_xds_push_timeout{job=\"pilot\"}[1m]))",
     "legendFormat": "Push Timeouts"
    },
    {
     "expr": "sum(rate(pilot_xds_push_timeout_failures{job=\"pilot\"}[1m]))",
     "legendFormat": "Push Timeouts Failures"
    }
   ]
  },
  {
   "title": "Proxy Push Time",
   "type": "graph",
   "description": "Shows the total time it takes to push a config update to a proxy",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pilot_conflict_inbound_listener{job=\"pilot\"}",
     "legendFormat": "Inbound Listeners"
    },
    {
     "expr": "pilot_conflict_outbound_listener_http_over_current_tcp{job=\"pilot\"}",
     "legendFormat": "Outbound Listeners (http over current tcp)"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_tcp{job=\"pilot\"}",
     "legendFormat": "Outbound Listeners (tcp over current tcp)"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_http{job=\"pilot\"}",
     "legendFormat": "Outbound Listeners (tcp over current http)"
    }
   ]
  },
  {
   "title": "ADS Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pilot_virt_services{job=\"pilot\"}",
     "legendFormat": "Virtual Services"
    },
    {
     "expr": "pilot_services{job=\"pilot\"}",
     "legendFormat": "Services"
    },
    {
     "expr": "pilot_xds{job=\"pilot\"}",
     "legendFormat": "Connected Endpoints"
    }
   ]
  },
  {
   "title": "Clusters with no known endpoints",
   "type": "table",
   "description": "Clusters in this table do not have any endpoints known to pilot. This could be from referencing subsets that do not have any instances, or pods marked as NotReady",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(pilot_xds_eds_instances{job=\"pilot\", cluster=~\".+\\\\|.+\"}) by (cluster) < 1",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Envoy Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Envoy Details",
   "type": "graph",
   "description": "Shows details about Envoy proxies in the mesh",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connections"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connection Failures"
    },
    {
     "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
     "legendFormat": "Envoy Restarts"
    }
   ]
  },
  {
   "title": "XDS Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
     "legendFormat": "XDS Active Connections"
    }
   ]
  },
  {
   "title": "XDS Requests Size",
   "type": "graph",
   "description": "Shows the size of XDS requests and responses",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Response Bytes Max"
    },
    {
     "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Response Bytes Average"
    },
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Max"
    },
    {
     "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Average"
    }
   ]
  }
 ]
}