filegroup(
    name = "addons",
    srcs = [
        "grafana.yaml",
        "logs.yaml",
        "metrics.yaml",
        "prometheus.yaml",
        "servicegraph.yaml",
        "zipkin.yaml",
        "zipkin-to-stackdriver.yaml",
    ],
    visibility = ["//visibility:public"],
)
