package(default_visibility = ["//visibility:public"])

filegroup(
    name = "descriptor_set",
    testonly = True,
    srcs = [
        "template_proto.descriptor_set",
    ],
)

filegroup(
    name = "golden_files",
    testonly = True,
    srcs = [
        "template_handler.gen.go.golden",
        "template_instance.proto.golden",
    ],
)
