#!/bin/bash
#
# Copyright 2016 Istio Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

if git rev-parse --verify --quiet HEAD >/dev/null; then
  echo "BUILD_SCM_REVISION $(git rev-parse --verify HEAD)"
else
  exit 1
fi

if git diff-index --quiet HEAD; then
  echo "BUILD_SCM_STATUS Clean"
else
  echo "BUILD_SCM_STATUS Modified"
fi
