#!/bin/bash

# Copyright Istio Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

WD=$(dirname "$0")
WD=$(cd "$WD"; pwd)
ROOT=$(dirname "$WD")

cd "${ROOT}"

set -eu

# Setup env vars
export $(./common/scripts/setup_env.sh envfile | xargs)
export REPO_ROOT="${ROOT}"

if [[ -f ${TARGET_OUT}/docker-builder ]]; then
  CURRENT_BUILD="$(./common/scripts/report_build_info.sh | grep buildGitRevision | cut -d= -f2)"
  PREBUILT="$(${TARGET_OUT}/docker-builder --version)"
  CODE_CHG="$(git diff ./tools/docker-builder)"
  if [[ "${CURRENT_BUILD}" != "${PREBUILT}" ]] || [[ -n "${CODE_CHG}" ]]; then
    GOOS=${TARGET_OS} GOARCH=${TARGET_ARCH} ./common/scripts/gobuild.sh ${TARGET_OUT}/docker-builder ./tools/docker-builder
  fi
else
  GOOS=${TARGET_OS} GOARCH=${TARGET_ARCH} ./common/scripts/gobuild.sh ${TARGET_OUT}/docker-builder ./tools/docker-builder
fi
${TARGET_OUT}/docker-builder "$@"
