#! /bin/bash
# update and rebuild from source
set -e
set -x
cd istio
git pull
cd ../mixer
git pull
cd ../proxy
git pull
cd ../wrk
git pull
make
cd ../proxy
bazel build src/envoy/mixer:envoy
cd ../mixer
bazel build cmd/server:mixs
set +x
echo "### All done... source istio/devel/setup_run   now"
