# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

FROM scratch as default

FROM gcr.io/distroless/static as distroless

FROM ${BASE_DISTRIBUTION}

# All containers need a /tmp directory
WORKDIR /tmp/
ADD node_agent /usr/local/bin/node_agent

ENTRYPOINT [ "/usr/local/bin/node_agent"]
