# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

FROM scratch as default
# obtained from debian ca-certs deb using fetch_cacerts.sh
ADD ca-certificates.tgz /

FROM gcr.io/distroless/static as distroless

FROM ${BASE_DISTRIBUTION}

# All containers need a /tmp directory
WORKDIR /tmp/
ADD istio_ca /usr/local/bin/istio_ca

ENTRYPOINT [ "/usr/local/bin/istio_ca", "--self-signed-ca" ]
