# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=ubuntu
FROM docker.io/istio/base:${BASE_VERSION} as ubuntu

COPY sdsclient /
RUN chmod 755 /sdsclient
ENTRYPOINT ["/sdsclient"]
