FROM alpine:3.7

RUN mkdir -p /usr/local/bin
ADD start_flexvolumedriver.sh /usr/local/bin/
ADD flexvolumedriver /usr/local/bin/

RUN chmod +x /usr/local/bin/start_flexvolumedriver.sh

ENTRYPOINT ["/usr/local/bin/start_flexvolumedriver.sh"]
