# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM docker.io/istio/base:${BASE_VERSION} as default

COPY istio_ca /usr/local/bin/istio_ca
COPY istio_ca.crt /usr/local/bin/istio_ca.crt
COPY istio_ca.key /usr/local/bin/istio_ca.key


ENTRYPOINT [ "/usr/local/bin/istio_ca", \
"--signing-cert", "/usr/local/bin/istio_ca.crt", \
"--signing-key", "/usr/local/bin/istio_ca.key", \
"--root-cert", "/usr/local/bin/istio_ca.crt", \
"--grpc-port", "8060" ]
