FROM ubuntu:xenial

ADD istio_ca /usr/local/bin/istio_ca

COPY istio_ca.crt /usr/local/bin/istio_ca.crt
COPY istio_ca.key /usr/local/bin/istio_ca.key
COPY reviewer-token.jwt /usr/local/bin/reviewer-token.jwt

ENTRYPOINT [ "/usr/local/bin/istio_ca", \
"--use-vault", \
"--reviewer-token-file", "/usr/local/bin/reviewer-token.jwt", \
"--vault-ip", "35.233.139.234", \
"--vault-port", "8200", \
"--grpc-host-identities", "istio-standalone-citadel.default.svc.cluster.local", \
"--signing-cert", "/usr/local/bin/istio_ca.crt", \
"--signing-key", "/usr/local/bin/istio_ca.key", \
"--root-cert", "/usr/local/bin/istio_ca.crt", \
"--grpc-hostname", "istio-citadel", \
"--grpc-port", "8060" ]

