# ISTIO_VERSION is used to specify the version of the release
ARG ISTIO_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM docker.io/istio/base:${ISTIO_VERSION} as default

COPY sdsclient /
RUN chmod 755 /sdsclient
ENTRYPOINT ["/sdsclient"]
