filegroup(
    name = "bookinfo",
    srcs = [
        "bookinfo.yaml",
        "route-rule-all-v1.yaml",
        "route-rule-delay.yaml",
        "route-rule-reviews-50-v3.yaml",
        "route-rule-reviews-test-v2.yaml",
    ],
    visibility = ["//visibility:public"],
)
