set -ex

echo ${JUNIT_REPORT} ${JUNIT_OUT}
{
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./pilot/pkg/networking/core/v1alpha3/...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./pilot/pkg/networking/core/v1alpha3/...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./pilot/pkg/networking/core/v1alpha3/...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./pilot/pkg/networking/core/v1alpha3/...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./pilot/pkg/networking/core/v1alpha3/...
} 2>&1 | tee >(${JUNIT_REPORT} > ${JUNIT_OUT})