set -ex

echo ${JUNIT_REPORT} ${JUNIT_OUT}
{
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
  		go test ${GOBUILDFLAGS} ${T} -count 1 -race ./...
} 2>&1 | tee >(${JUNIT_REPORT} > ${JUNIT_OUT})