load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["types.go"],
    visibility = ["//visibility:public"],
    deps = ["//pkg/attribute:go_default_library"],
)
